// Shared question data used by the practice quiz (quiz.html), the
// per-element quizzes (element-quiz.html), and the daily quiz
// (daily-quiz.html), which blends questions from both pools.

// Pool of 100 questions for the practice quiz.
export const PRACTICE_QUESTIONS = [
      { q: "What is the chemical symbol for gold?", qTh: "สัญลักษณ์ทางเคมีของทองคำคืออะไร", choices: ["Au", "Ag", "Gd", "Go"], choicesTh: ["Au", "Ag", "Gd", "Go"], correct: 0 },
      { q: "Which element has the atomic number 1?", qTh: "ธาตุใดมีเลขอะตอมเท่ากับ 1", choices: ["Hydrogen", "Helium", "Oxygen", "Carbon"], choicesTh: ["ไฮโดรเจน", "ฮีเลียม", "ออกซิเจน", "คาร์บอน"], correct: 0 },
      { q: "What do we call elements like helium, neon, and argon that rarely react with other elements?", qTh: "เราเรียกธาตุอย่างฮีเลียม นีออน และอาร์กอน ที่แทบไม่ทำปฏิกิริยากับธาตุอื่นว่าอะไร", choices: ["Noble gases", "Alkali metals", "Halogens", "Metalloids"], choicesTh: ["แก๊สมีตระกูล", "โลหะแอลคาไล", "ธาตุแฮโลเจน", "ธาตุกึ่งโลหะ"], correct: 0 },
      { q: "Which element makes up about 21% of Earth's atmosphere and is essential for breathing?", qTh: "ธาตุใดคิดเป็นประมาณ 21% ของบรรยากาศโลก และจำเป็นต่อการหายใจ", choices: ["Oxygen", "Nitrogen", "Carbon", "Hydrogen"], choicesTh: ["ออกซิเจน", "ไนโตรเจน", "คาร์บอน", "ไฮโดรเจน"], correct: 0 },
      { q: "What is the most abundant element in the universe?", qTh: "ธาตุใดมีมากที่สุดในเอกภพ", choices: ["Hydrogen", "Helium", "Oxygen", "Carbon"], choicesTh: ["ไฮโดรเจน", "ฮีเลียม", "ออกซิเจน", "คาร์บอน"], correct: 0 },
      { q: "Which of these elements is a liquid at room temperature?", qTh: "ธาตุใดต่อไปนี้เป็นของเหลวที่อุณหภูมิห้อง", choices: ["Mercury", "Iron", "Sodium", "Sulfur"], choicesTh: ["ปรอท", "เหล็ก", "โซเดียม", "กำมะถัน"], correct: 0 },
      { q: "What is the chemical symbol for iron?", qTh: "สัญลักษณ์ทางเคมีของเหล็กคืออะไร", choices: ["Fe", "Ir", "In", "I"], choicesTh: ["Fe", "Ir", "In", "I"], correct: 0 },
      { q: "Which group contains extremely reactive metals like sodium and potassium?", qTh: "หมู่ใดประกอบด้วยโลหะที่ว่องไวต่อปฏิกิริยาอย่างมาก เช่น โซเดียมและโพแทสเซียม", choices: ["Alkali metals", "Noble gases", "Halogens", "Transition metals"], choicesTh: ["โลหะแอลคาไล", "แก๊สมีตระกูล", "ธาตุแฮโลเจน", "โลหะทรานซิชัน"], correct: 0 },
      { q: "The number of protons in an atom's nucleus is called its...", qTh: "จำนวนโปรตอนในนิวเคลียสของอะตอมเรียกว่าอะไร", choices: ["Atomic number", "Atomic mass", "Valence number", "Isotope number"], choicesTh: ["เลขอะตอม", "มวลอะตอม", "เลขวาเลนซ์", "เลขไอโซโทป"], correct: 0 },
      { q: "Plants use this element (from carbon dioxide) to build food during photosynthesis.", qTh: "พืชใช้ธาตุนี้ (จากคาร์บอนไดออกไซด์) เพื่อสร้างอาหารในกระบวนการสังเคราะห์แสง", choices: ["Carbon", "Nitrogen", "Neon", "Sulfur"], choicesTh: ["คาร์บอน", "ไนโตรเจน", "นีออน", "กำมะถัน"], correct: 0 },
      { q: "Sonic Scholar has a song about the element used to make computer chips and found in sand. What is it?", qTh: "Sonic Scholar มีเพลงเกี่ยวกับธาตุที่ใช้ทำชิปคอมพิวเตอร์และพบในทราย ธาตุนี้คืออะไร", choices: ["Silicon", "Carbon", "Sulfur", "Silver"], choicesTh: ["ซิลิคอน", "คาร์บอน", "กำมะถัน", "เงิน"], correct: 0, song: true },
      { q: "Which of these is a halogen, a group of reactive nonmetals often used in cleaning products?", qTh: "ข้อใดต่อไปนี้เป็นธาตุแฮโลเจน ซึ่งเป็นกลุ่มอโลหะที่ว่องไวต่อปฏิกิริยาและมักใช้ในผลิตภัณฑ์ทำความสะอาด", choices: ["Chlorine", "Sodium", "Argon", "Iron"], choicesTh: ["คลอรีน", "โซเดียม", "อาร์กอน", "เหล็ก"], correct: 0 },
      { q: "What is the chemical symbol for sodium?", qTh: "สัญลักษณ์ทางเคมีของโซเดียมคืออะไร", choices: ["Na", "So", "Sd", "Sn"], choicesTh: ["Na", "So", "Sd", "Sn"], correct: 0 },
      { q: "Which element is named after the sun and was spotted in the sun's spectrum before it was found on Earth?", qTh: "ธาตุใดตั้งชื่อตามดวงอาทิตย์ และถูกพบในสเปกตรัมของดวงอาทิตย์ก่อนที่จะพบบนโลก", choices: ["Helium", "Neon", "Argon", "Solarium"], choicesTh: ["ฮีเลียม", "นีออน", "อาร์กอน", "โซลาเรียม"], correct: 0 },
      { q: "What state of matter is neon at room temperature?", qTh: "นีออนอยู่ในสถานะใดที่อุณหภูมิห้อง", choices: ["Gas", "Solid", "Liquid", "Plasma"], choicesTh: ["แก๊ส", "ของแข็ง", "ของเหลว", "พลาสมา"], correct: 0 },
      { q: "This soft metal reacts violently with water and is found in table salt.", qTh: "โลหะอ่อนชนิดนี้ทำปฏิกิริยารุนแรงกับน้ำ และพบได้ในเกลือแกง", choices: ["Sodium", "Chlorine", "Iron", "Calcium"], choicesTh: ["โซเดียม", "คลอรีน", "เหล็ก", "แคลเซียม"], correct: 0 },
      { q: "Who created the first widely-used version of the periodic table in 1869?", qTh: "ใครเป็นผู้สร้างตารางธาตุฉบับแรกที่ใช้กันแพร่หลายในปี ค.ศ. 1869", choices: ["Dmitri Mendeleev", "Marie Curie", "Albert Einstein", "Isaac Newton"], choicesTh: ["Dmitri Mendeleev", "Marie Curie", "Albert Einstein", "Isaac Newton"], correct: 0 },
      { q: "The symbol Pb comes from the Latin word \"plumbum.\" Which element is it?", qTh: "สัญลักษณ์ Pb มาจากคำในภาษาละตินว่า \"plumbum\" ธาตุนี้คือธาตุใด", choices: ["Lead", "Platinum", "Phosphorus", "Palladium"], choicesTh: ["ตะกั่ว", "แพลตทินัม", "ฟอสฟอรัส", "แพลเลเดียม"], correct: 0 },
      { q: "Sonic Scholar has a song about element #6, the basis of all known life on Earth. What is it?", qTh: "Sonic Scholar มีเพลงเกี่ยวกับธาตุลำดับที่ 6 ซึ่งเป็นพื้นฐานของสิ่งมีชีวิตทั้งหมดที่รู้จักบนโลก ธาตุนี้คืออะไร", choices: ["Carbon", "Oxygen", "Silicon", "Nitrogen"], choicesTh: ["คาร์บอน", "ออกซิเจน", "ซิลิคอน", "ไนโตรเจน"], correct: 0, song: true },
      { q: "Which family includes fluorine, chlorine, bromine, and iodine?", qTh: "ธาตุตระกูลใดที่รวมฟลูออรีน คลอรีน โบรมีน และไอโอดีนไว้ด้วยกัน", choices: ["Halogens", "Noble gases", "Alkaline earth metals", "Lanthanides"], choicesTh: ["ธาตุแฮโลเจน", "แก๊สมีตระกูล", "โลหะแอลคาไลน์เอิร์ท", "แลนทาไนด์"], correct: 0 },
      { q: "What is the chemical symbol for potassium?", qTh: "สัญลักษณ์ทางเคมีของโพแทสเซียมคืออะไร", choices: ["K", "Po", "Pt", "Ps"], choicesTh: ["K", "Po", "Pt", "Ps"], correct: 0 },
      { q: "Which glowing, radioactive element was discovered by Marie and Pierre Curie and later used in glow-in-the-dark paint?", qTh: "ธาตุกัมมันตรังสีเรืองแสงชนิดใดที่มารีและปีแยร์ กูว์รี ค้นพบ และภายหลังถูกนำไปใช้ในสีเรืองแสงในที่มืด", choices: ["Radium", "Radon", "Uranium", "Thorium"], choicesTh: ["เรเดียม", "เรดอน", "ยูเรเนียม", "ทอเรียม"], correct: 0 },
      { q: "How many valence electrons does an atom in Group 1 (like hydrogen or sodium) typically have?", qTh: "อะตอมในหมู่ที่ 1 (เช่น ไฮโดรเจนหรือโซเดียม) มักมีอิเล็กตรอนวาเลนซ์กี่ตัว", choices: ["1", "2", "7", "8"], choicesTh: ["1", "2", "7", "8"], correct: 0 },
      { q: "Which element is a metalloid, meaning it has properties of both metals and nonmetals?", qTh: "ธาตุใดเป็นธาตุกึ่งโลหะ ซึ่งหมายถึงมีสมบัติทั้งของโลหะและอโลหะ", choices: ["Silicon", "Iron", "Oxygen", "Sodium"], choicesTh: ["ซิลิคอน", "เหล็ก", "ออกซิเจน", "โซเดียม"], correct: 0 },
      { q: "Sonic Scholar has a song about the lightest metal on the periodic table, used in phone batteries. What is it?", qTh: "Sonic Scholar มีเพลงเกี่ยวกับโลหะที่เบาที่สุดในตารางธาตุ ซึ่งใช้ในแบตเตอรี่โทรศัพท์ ธาตุนี้คืออะไร", choices: ["Lithium", "Lead", "Iron", "Tin"], choicesTh: ["ลิเธียม", "ตะกั่ว", "เหล็ก", "ดีบุก"], correct: 0, song: true },
      { q: "Which element is the second-lightest element on the whole periodic table, and is used to fill balloons because it's safe and non-flammable?", qTh: "ธาตุใดเบาเป็นอันดับสองในตารางธาตุทั้งหมด และถูกใช้เติมลูกโป่งเพราะปลอดภัยและไม่ติดไฟ", choices: ["Helium", "Hydrogen", "Neon", "Argon"], choicesTh: ["ฮีเลียม", "ไฮโดรเจน", "นีออน", "อาร์กอน"], correct: 0 },
      { q: "Which two elements combine to form water (H2O)?", qTh: "ธาตุสองชนิดใดรวมกันเป็นน้ำ (H2O)", choices: ["Hydrogen and Oxygen", "Helium and Oxygen", "Hydrogen and Nitrogen", "Carbon and Oxygen"], choicesTh: ["ไฮโดรเจนและออกซิเจน", "ฮีเลียมและออกซิเจน", "ไฮโดรเจนและไนโตรเจน", "คาร์บอนและออกซิเจน"], correct: 0 },
      { q: "The two rows usually placed below the main periodic table are called...", qTh: "สองแถวที่มักวางไว้ด้านล่างของตารางธาตุหลักเรียกว่าอะไร", choices: ["Lanthanides and actinides", "Transition metals", "Noble gases", "Halogens"], choicesTh: ["แลนทาไนด์และแอกทิไนด์", "โลหะทรานซิชัน", "แก๊สมีตระกูล", "ธาตุแฮโลเจน"], correct: 0 },
      { q: "Which element is important for strong bones and teeth, and is found in milk?", qTh: "ธาตุใดสำคัญต่อความแข็งแรงของกระดูกและฟัน และพบได้ในนม", choices: ["Calcium", "Iron", "Potassium", "Sodium"], choicesTh: ["แคลเซียม", "เหล็ก", "โพแทสเซียม", "โซเดียม"], correct: 0 },
      { q: "Sonic Scholar has a song about the element that gives blood its red color and helps it carry oxygen. What is it?", qTh: "Sonic Scholar มีเพลงเกี่ยวกับธาตุที่ทำให้เลือดมีสีแดงและช่วยลำเลียงออกซิเจน ธาตุนี้คืออะไร", choices: ["Iron", "Copper", "Zinc", "Calcium"], choicesTh: ["เหล็ก", "ทองแดง", "สังกะสี", "แคลเซียม"], correct: 0, song: true },

      // More element facts
      { q: "What is the chemical symbol for tungsten, the metal with the highest melting point of any element?", qTh: "สัญลักษณ์ทางเคมีของทังสเตน ซึ่งเป็นโลหะที่มีจุดหลอมเหลวสูงที่สุดในบรรดาธาตุทั้งหมดคืออะไร", choices: ["W", "Tu", "Tn", "Wf"], choicesTh: ["W", "Tu", "Tn", "Wf"], correct: 0 },
      { q: "What is the chemical symbol for tin?", qTh: "สัญลักษณ์ทางเคมีของดีบุกคืออะไร", choices: ["Sn", "Ti", "Tn", "To"], choicesTh: ["Sn", "Ti", "Tn", "To"], correct: 0 },
      { q: "What is the chemical symbol for silver?", qTh: "สัญลักษณ์ทางเคมีของเงินคืออะไร", choices: ["Ag", "Si", "Sv", "Ar"], choicesTh: ["Ag", "Si", "Sv", "Ar"], correct: 0 },
      { q: "What is the chemical symbol for copper?", qTh: "สัญลักษณ์ทางเคมีของทองแดงคืออะไร", choices: ["Cu", "Co", "Cp", "Cr"], choicesTh: ["Cu", "Co", "Cp", "Cr"], correct: 0 },
      { q: "What is the chemical symbol for mercury, the only metal that's liquid at room temperature?", qTh: "สัญลักษณ์ทางเคมีของปรอท ซึ่งเป็นโลหะชนิดเดียวที่เป็นของเหลวที่อุณหภูมิห้องคืออะไร", choices: ["Hg", "Me", "Mc", "Hy"], choicesTh: ["Hg", "Me", "Mc", "Hy"], correct: 0 },
      { q: "Which halogen is added to drinking water and toothpaste to help prevent tooth decay?", qTh: "ธาตุแฮโลเจนชนิดใดถูกเติมลงในน้ำดื่มและยาสีฟันเพื่อช่วยป้องกันฟันผุ", choices: ["Fluorine", "Chlorine", "Iodine", "Bromine"], choicesTh: ["ฟลูออรีน", "คลอรีน", "ไอโอดีน", "โบรมีน"], correct: 0 },
      { q: "Which element is essential for the thyroid gland and is often added to table salt?", qTh: "ธาตุใดจำเป็นต่อต่อมไทรอยด์ และมักถูกเติมลงในเกลือแกง", choices: ["Iodine", "Iron", "Zinc", "Fluorine"], choicesTh: ["ไอโอดีน", "เหล็ก", "สังกะสี", "ฟลูออรีน"], correct: 0 },
      { q: "What is the chemical symbol for zinc?", qTh: "สัญลักษณ์ทางเคมีของสังกะสีคืออะไร", choices: ["Zn", "Zi", "Zc", "Zk"], choicesTh: ["Zn", "Zi", "Zc", "Zk"], correct: 0 },
      { q: "What is the chemical symbol for platinum?", qTh: "สัญลักษณ์ทางเคมีของแพลตทินัมคืออะไร", choices: ["Pt", "Pl", "Pn", "Po"], choicesTh: ["Pt", "Pl", "Pn", "Po"], correct: 0 },
      { q: "Which radioactive gas is a natural byproduct of uranium decay and can build up in basements?", qTh: "แก๊สกัมมันตรังสีชนิดใดเกิดขึ้นตามธรรมชาติจากการสลายตัวของยูเรเนียม และสามารถสะสมอยู่ในห้องใต้ดินได้", choices: ["Radon", "Radium", "Xenon", "Krypton"], choicesTh: ["เรดอน", "เรเดียม", "ซีนอน", "คริปทอน"], correct: 0 },
      { q: "Which element is a key ingredient in bones and teeth, along with calcium, and is also part of DNA?", qTh: "ธาตุใดเป็นส่วนประกอบสำคัญของกระดูกและฟันควบคู่กับแคลเซียม และยังเป็นส่วนหนึ่งของ DNA ด้วย", choices: ["Phosphorus", "Sulfur", "Nitrogen", "Potassium"], choicesTh: ["ฟอสฟอรัส", "กำมะถัน", "ไนโตรเจน", "โพแทสเซียม"], correct: 0 },
      { q: "Which element is famous for its rotten-egg smell in compounds like hydrogen sulfide?", qTh: "ธาตุใดขึ้นชื่อเรื่องกลิ่นเหม็นเหมือนไข่เน่าในสารประกอบอย่างไฮโดรเจนซัลไฟด์", choices: ["Sulfur", "Selenium", "Silicon", "Sodium"], choicesTh: ["กำมะถัน", "ซีลีเนียม", "ซิลิคอน", "โซเดียม"], correct: 0 },
      { q: "Which family of elements, including lanthanum and cerium, is often used in magnets, batteries, and phone screens?", qTh: "ธาตุตระกูลใดที่รวมแลนทานัมและซีเรียม มักถูกนำไปใช้ในแม่เหล็ก แบตเตอรี่ และหน้าจอโทรศัพท์", choices: ["Lanthanides", "Actinides", "Halogens", "Alkali metals"], choicesTh: ["แลนทาไนด์", "แอกทิไนด์", "ธาตุแฮโลเจน", "โลหะแอลคาไล"], correct: 0 },
      { q: "Which family of elements includes uranium and plutonium, and is mostly radioactive?", qTh: "ธาตุตระกูลใดที่รวมยูเรเนียมและพลูโทเนียม และส่วนใหญ่มีกัมมันตรังสี", choices: ["Actinides", "Lanthanides", "Noble gases", "Transition metals"], choicesTh: ["แอกทิไนด์", "แลนทาไนด์", "แก๊สมีตระกูล", "โลหะทรานซิชัน"], correct: 0 },
      { q: "Iron, copper, and gold all belong to the large middle block of the periodic table. What is this block called?", qTh: "เหล็ก ทองแดง และทองคำ ล้วนอยู่ในบล็อกกลางขนาดใหญ่ของตารางธาตุ บล็อกนี้เรียกว่าอะไร", choices: ["Transition metals", "Alkali metals", "Metalloids", "Halogens"], choicesTh: ["โลหะทรานซิชัน", "โลหะแอลคาไล", "ธาตุกึ่งโลหะ", "ธาตุแฮโลเจน"], correct: 0 },
      { q: "Which group on the periodic table is known as the alkaline earth metals?", qTh: "หมู่ใดในตารางธาตุที่รู้จักกันในชื่อโลหะแอลคาไลน์เอิร์ท", choices: ["Group 2", "Group 1", "Group 17", "Group 18"], choicesTh: ["หมู่ที่ 2", "หมู่ที่ 1", "หมู่ที่ 17", "หมู่ที่ 18"], correct: 0 },
      { q: "What is the term for the vertical columns on the periodic table?", qTh: "คอลัมน์แนวตั้งในตารางธาตุเรียกว่าอะไร", choices: ["Groups", "Periods", "Rows", "Series"], choicesTh: ["หมู่", "คาบ", "แถว", "อนุกรม"], correct: 0 },
      { q: "What is the term for the horizontal rows on the periodic table?", qTh: "แถวแนวนอนในตารางธาตุเรียกว่าอะไร", choices: ["Periods", "Groups", "Columns", "Families"], choicesTh: ["คาบ", "หมู่", "คอลัมน์", "ตระกูล"], correct: 0 },
      { q: "What is the chemical symbol for barium?", qTh: "สัญลักษณ์ทางเคมีของแบเรียมคืออะไร", choices: ["Ba", "Br", "Bo", "By"], choicesTh: ["Ba", "Br", "Bo", "By"], correct: 0 },
      { q: "What is the chemical symbol for titanium, a strong, lightweight metal used in jet engines and bikes?", qTh: "สัญลักษณ์ทางเคมีของไทเทเนียม ซึ่งเป็นโลหะที่แข็งแรงและมีน้ำหนักเบา ใช้ในเครื่องยนต์เจ็ตและจักรยานคืออะไร", choices: ["Ti", "Ta", "Tn", "To"], choicesTh: ["Ti", "Ta", "Tn", "To"], correct: 0 },
      { q: "Which noble gas, symbol Kr, is used to fill some energy-efficient light bulbs and lasers?", qTh: "แก๊สมีตระกูลชนิดใด ที่มีสัญลักษณ์ Kr ถูกใช้เติมในหลอดไฟประหยัดพลังงานและเลเซอร์บางชนิด", choices: ["Krypton", "Xenon", "Argon", "Radon"], choicesTh: ["คริปทอน", "ซีนอน", "อาร์กอน", "เรดอน"], correct: 0 },
      { q: "Which element is used in fireworks to make bright red flames?", qTh: "ธาตุใดถูกใช้ในดอกไม้ไฟเพื่อทำให้เกิดเปลวไฟสีแดงสด", choices: ["Strontium", "Barium", "Calcium", "Radium"], choicesTh: ["สทรอนเชียม", "แบเรียม", "แคลเซียม", "เรเดียม"], correct: 0 },
      { q: "Copper, silver, and gold all share a column on the periodic table. What is this group sometimes nicknamed?", qTh: "ทองแดง เงิน และทองคำ อยู่ในคอลัมน์เดียวกันของตารางธาตุ หมู่นี้มีชื่อเล่นว่าอะไร", choices: ["The coinage metals", "The noble metals", "The alkali metals", "The halogens"], choicesTh: ["โลหะเหรียญกษาปณ์", "โลหะมีตระกูล", "โลหะแอลคาไล", "ธาตุแฮโลเจน"], correct: 0 },
      { q: "Which gas makes up about 78% of Earth's atmosphere, more than any other gas?", qTh: "แก๊สใดคิดเป็นประมาณ 78% ของบรรยากาศโลก มากกว่าแก๊สชนิดอื่นใด", choices: ["Nitrogen", "Oxygen", "Argon", "Carbon dioxide"], choicesTh: ["ไนโตรเจน", "ออกซิเจน", "อาร์กอน", "คาร์บอนไดออกไซด์"], correct: 0 },
      { q: "What is the term for a pure substance made of only one type of atom?", qTh: "สารบริสุทธิ์ที่ประกอบด้วยอะตอมชนิดเดียวเท่านั้นเรียกว่าอะไร", choices: ["An element", "A compound", "A mixture", "A molecule"], choicesTh: ["ธาตุ", "สารประกอบ", "ของผสม", "โมเลกุล"], correct: 0 },
      { q: "What is the term for a pure substance made of two or more different elements chemically bonded together?", qTh: "สารบริสุทธิ์ที่ประกอบด้วยธาตุตั้งแต่สองชนิดขึ้นไปที่เกิดพันธะทางเคมีร่วมกันเรียกว่าอะไร", choices: ["A compound", "An element", "A mixture", "An isotope"], choicesTh: ["สารประกอบ", "ธาตุ", "ของผสม", "ไอโซโทป"], correct: 0 },
      { q: "Which of these is a physical change rather than a chemical change?", qTh: "ข้อใดต่อไปนี้เป็นการเปลี่ยนแปลงทางกายภาพ ไม่ใช่การเปลี่ยนแปลงทางเคมี", choices: ["Melting ice", "Rusting iron", "Burning wood", "Baking a cake"], choicesTh: ["น้ำแข็งละลาย", "เหล็กเกิดสนิม", "ไม้ถูกเผาไหม้", "การอบเค้ก"], correct: 0 },
      { q: "Which of these is a chemical change rather than a physical change?", qTh: "ข้อใดต่อไปนี้เป็นการเปลี่ยนแปลงทางเคมี ไม่ใช่การเปลี่ยนแปลงทางกายภาพ", choices: ["Rusting iron", "Melting ice", "Boiling water", "Dissolving sugar in water"], choicesTh: ["เหล็กเกิดสนิม", "น้ำแข็งละลาย", "น้ำเดือด", "น้ำตาลละลายในน้ำ"], correct: 0 },

      // Harder questions for high schoolers: atomic structure, bonding, and reactions
      { q: "What do we call atoms of the same element that have different numbers of neutrons?", qTh: "อะตอมของธาตุชนิดเดียวกันที่มีจำนวนนิวตรอนต่างกันเรียกว่าอะไร", choices: ["Isotopes", "Ions", "Isomers", "Isobars"], choicesTh: ["ไอโซโทป", "ไอออน", "ไอโซเมอร์", "ไอโซบาร์"], correct: 0 },
      { q: "Which subatomic particle carries a negative electric charge?", qTh: "อนุภาคย่อยของอะตอมชนิดใดมีประจุไฟฟ้าลบ", choices: ["Electron", "Proton", "Neutron", "Positron"], choicesTh: ["อิเล็กตรอน", "โปรตอน", "นิวตรอน", "โพซิตรอน"], correct: 0 },
      { q: "Which type of bond forms when electrons are transferred from one atom to another, like between sodium and chlorine?", qTh: "พันธะชนิดใดเกิดขึ้นเมื่อมีการถ่ายโอนอิเล็กตรอนจากอะตอมหนึ่งไปยังอีกอะตอมหนึ่ง เช่น ระหว่างโซเดียมกับคลอรีน", choices: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"], choicesTh: ["พันธะไอออนิก", "พันธะโคเวเลนต์", "พันธะโลหะ", "พันธะไฮโดรเจน"], correct: 0 },
      { q: "Which type of bond forms when atoms share electrons, like in a water molecule?", qTh: "พันธะชนิดใดเกิดขึ้นเมื่ออะตอมใช้อิเล็กตรอนร่วมกัน เช่น ในโมเลกุลน้ำ", choices: ["Covalent bond", "Ionic bond", "Metallic bond", "Van der Waals bond"], choicesTh: ["พันธะโคเวเลนต์", "พันธะไอออนิก", "พันธะโลหะ", "พันธะแวนเดอร์วาลส์"], correct: 0 },
      { q: "On the pH scale, a solution with a pH of 3 is considered...?", qTh: "บนสเกล pH สารละลายที่มีค่า pH เท่ากับ 3 ถือว่าเป็นอย่างไร", choices: ["Acidic", "Basic", "Neutral", "Radioactive"], choicesTh: ["เป็นกรด", "เป็นเบส", "เป็นกลาง", "มีกัมมันตรังสี"], correct: 0 },
      { q: "Which particle is emitted during alpha decay?", qTh: "อนุภาคใดถูกปล่อยออกมาในระหว่างการสลายตัวแบบแอลฟา", choices: ["A helium nucleus (2 protons, 2 neutrons)", "A high-energy electron", "A gamma ray", "A neutron"], choicesTh: ["นิวเคลียสของฮีเลียม (โปรตอน 2 ตัว นิวตรอน 2 ตัว)", "อิเล็กตรอนพลังงานสูง", "รังสีแกมมา", "นิวตรอน"], correct: 0 },
      { q: "What is the term for the amount of time it takes for half of a radioactive sample to decay?", qTh: "ระยะเวลาที่ตัวอย่างสารกัมมันตรังสีสลายตัวไปครึ่งหนึ่งเรียกว่าอะไร", choices: ["Half-life", "Decay rate", "Isotope period", "Atomic clock"], choicesTh: ["ครึ่งชีวิต", "อัตราการสลายตัว", "คาบไอโซโทป", "นาฬิกาอะตอม"], correct: 0 },
      { q: "A mole of any substance contains approximately how many particles? (Avogadro's number)", qTh: "สารหนึ่งโมลไม่ว่าชนิดใดมีจำนวนอนุภาคประมาณเท่าใด (เลขอาโวกาโดร)", choices: ["6.02 x 10^23", "3.14 x 10^23", "1.0 x 10^23", "9.8 x 10^23"], choicesTh: ["6.02 x 10^23", "3.14 x 10^23", "1.0 x 10^23", "9.8 x 10^23"], correct: 0 },
      { q: "Which scientist's model of the atom pictured a small, dense, positively charged nucleus surrounded by mostly empty space?", qTh: "แบบจำลองอะตอมของนักวิทยาศาสตร์คนใดที่แสดงนิวเคลียสขนาดเล็ก หนาแน่น มีประจุบวก ล้อมรอบด้วยพื้นที่ว่างเป็นส่วนใหญ่", choices: ["Ernest Rutherford", "J.J. Thomson", "Niels Bohr", "John Dalton"], choicesTh: ["Ernest Rutherford", "J.J. Thomson", "Niels Bohr", "John Dalton"], correct: 0 },
      { q: "In a redox reaction, what does the term 'oxidation' mean?", qTh: "ในปฏิกิริยารีดอกซ์ คำว่า \"ออกซิเดชัน\" หมายถึงอะไร", choices: ["Losing electrons", "Gaining electrons", "Gaining protons", "Losing neutrons"], choicesTh: ["การเสียอิเล็กตรอน", "การรับอิเล็กตรอน", "การรับโปรตอน", "การเสียนิวตรอน"], correct: 0 },

      // 8th grade level questions: atomic structure, properties, and everyday elements
      { q: "Which subatomic particle has a positive electric charge?", qTh: "อนุภาคย่อยของอะตอมชนิดใดมีประจุไฟฟ้าบวก", choices: ["Proton", "Electron", "Neutron", "Ion"], choicesTh: ["โปรตอน", "อิเล็กตรอน", "นิวตรอน", "ไอออน"], correct: 0 },
      { q: "Which subatomic particle has no electric charge?", qTh: "อนุภาคย่อยของอะตอมชนิดใดไม่มีประจุไฟฟ้า", choices: ["Neutron", "Proton", "Electron", "Ion"], choicesTh: ["นิวตรอน", "โปรตอน", "อิเล็กตรอน", "ไอออน"], correct: 0 },
      { q: "Where in an atom would you find its protons and neutrons?", qTh: "โปรตอนและนิวตรอนของอะตอมอยู่ที่ส่วนใด", choices: ["In the nucleus", "In the electron cloud", "Outside the atom", "In the valence shell"], choicesTh: ["ในนิวเคลียส", "ในกลุ่มหมอกอิเล็กตรอน", "นอกอะตอม", "ในเปลือกวาเลนซ์"], correct: 0 },
      { q: "Where in an atom would you find its electrons?", qTh: "อิเล็กตรอนของอะตอมอยู่ที่ส่วนใด", choices: ["Moving around the nucleus in an electron cloud", "Packed tightly in the nucleus", "Outside the atom entirely", "In the atomic number"], choicesTh: ["เคลื่อนที่รอบนิวเคลียสในกลุ่มหมอกอิเล็กตรอน", "อัดแน่นอยู่ในนิวเคลียส", "อยู่นอกอะตอมทั้งหมด", "อยู่ในเลขอะตอม"], correct: 0 },
      { q: "What is the term for how much mass is packed into a given volume of a substance?", qTh: "ปริมาณมวลที่บรรจุอยู่ในปริมาตรหนึ่งของสารเรียกว่าอะไร", choices: ["Density", "Weight", "Buoyancy", "Viscosity"], choicesTh: ["ความหนาแน่น", "น้ำหนัก", "แรงลอยตัว", "ความหนืด"], correct: 0 },
      { q: "Which is denser: a bar of gold or a same-sized bar of aluminum?", qTh: "ระหว่างทองคำแท่งกับอะลูมิเนียมแท่งขนาดเท่ากัน อย่างใดมีความหนาแน่นมากกว่า", choices: ["Gold", "Aluminum", "They're the same", "Neither has density"], choicesTh: ["ทองคำ", "อะลูมิเนียม", "หนาแน่นเท่ากัน", "ไม่มีความหนาแน่นเลย"], correct: 0 },
      { q: "What is the temperature at which a solid turns into a liquid called?", qTh: "อุณหภูมิที่ของแข็งเปลี่ยนเป็นของเหลวเรียกว่าอะไร", choices: ["Melting point", "Boiling point", "Freezing point", "Condensation point"], choicesTh: ["จุดหลอมเหลว", "จุดเดือด", "จุดเยือกแข็ง", "จุดควบแน่น"], correct: 0 },
      { q: "What is the temperature at which a liquid turns into a gas called?", qTh: "อุณหภูมิที่ของเหลวเปลี่ยนเป็นแก๊สเรียกว่าอะไร", choices: ["Boiling point", "Melting point", "Freezing point", "Sublimation point"], choicesTh: ["จุดเดือด", "จุดหลอมเหลว", "จุดเยือกแข็ง", "จุดระเหิด"], correct: 0 },
      { q: "What do we call a combination of two or more substances that are physically mixed but not chemically bonded?", qTh: "การรวมกันของสารตั้งแต่สองชนิดขึ้นไปที่ผสมกันทางกายภาพแต่ไม่ได้เกิดพันธะทางเคมีเรียกว่าอะไร", choices: ["A mixture", "A compound", "An element", "An isotope"], choicesTh: ["ของผสม", "สารประกอบ", "ธาตุ", "ไอโซโทป"], correct: 0 },
      { q: "Salt dissolved evenly in water is an example of what kind of mixture?", qTh: "เกลือที่ละลายอย่างสม่ำเสมอในน้ำเป็นตัวอย่างของของผสมชนิดใด", choices: ["A solution", "A suspension", "A compound", "An isotope"], choicesTh: ["สารละลาย", "การแขวนลอย", "สารประกอบ", "ไอโซโทป"], correct: 0 },
      { q: "What is the chemical symbol for nitrogen?", qTh: "สัญลักษณ์ทางเคมีของไนโตรเจนคืออะไร", choices: ["N", "Ni", "No", "Na"], choicesTh: ["N", "Ni", "No", "Na"], correct: 0 },
      { q: "What is the chemical symbol for oxygen?", qTh: "สัญลักษณ์ทางเคมีของออกซิเจนคืออะไร", choices: ["O", "Ox", "Og", "Om"], choicesTh: ["O", "Ox", "Og", "Om"], correct: 0 },
      { q: "What is the chemical symbol for carbon?", qTh: "สัญลักษณ์ทางเคมีของคาร์บอนคืออะไร", choices: ["C", "Ca", "Co", "Cr"], choicesTh: ["C", "Ca", "Co", "Cr"], correct: 0 },
      { q: "What is the chemical symbol for helium?", qTh: "สัญลักษณ์ทางเคมีของฮีเลียมคืออะไร", choices: ["He", "H", "Hl", "Hu"], choicesTh: ["He", "H", "Hl", "Hu"], correct: 0 },
      { q: "What is the chemical symbol for neon?", qTh: "สัญลักษณ์ทางเคมีของนีออนคืออะไร", choices: ["Ne", "No", "N", "Nn"], choicesTh: ["Ne", "No", "N", "Nn"], correct: 0 },
      { q: "What is the chemical symbol for chlorine?", qTh: "สัญลักษณ์ทางเคมีของคลอรีนคืออะไร", choices: ["Cl", "Ch", "Co", "Cr"], choicesTh: ["Cl", "Ch", "Co", "Cr"], correct: 0 },
      { q: "What is the chemical symbol for calcium?", qTh: "สัญลักษณ์ทางเคมีของแคลเซียมคืออะไร", choices: ["Ca", "Cl", "Co", "Cm"], choicesTh: ["Ca", "Cl", "Co", "Cm"], correct: 0 },
      { q: "What is the chemical symbol for magnesium?", qTh: "สัญลักษณ์ทางเคมีของแมกนีเซียมคืออะไร", choices: ["Mg", "Ma", "Mn", "Mo"], choicesTh: ["Mg", "Ma", "Mn", "Mo"], correct: 0 },
      { q: "What is the chemical symbol for aluminum?", qTh: "สัญลักษณ์ทางเคมีของอะลูมิเนียมคืออะไร", choices: ["Al", "Am", "An", "Au"], choicesTh: ["Al", "Am", "An", "Au"], correct: 0 },
      { q: "What is the chemical symbol for lithium?", qTh: "สัญลักษณ์ทางเคมีของลิเธียมคืออะไร", choices: ["Li", "Lt", "Ln", "Lu"], choicesTh: ["Li", "Lt", "Ln", "Lu"], correct: 0 },
      { q: "Which gas do humans breathe in and use for energy, and which plants release during photosynthesis?", qTh: "แก๊สใดที่มนุษย์หายใจเข้าและใช้เพื่อสร้างพลังงาน และพืชปล่อยออกมาในกระบวนการสังเคราะห์แสง", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], choicesTh: ["ออกซิเจน", "คาร์บอนไดออกไซด์", "ไนโตรเจน", "ไฮโดรเจน"], correct: 0 },
      { q: "Which gas do humans breathe out as a waste product, and plants take in for photosynthesis?", qTh: "แก๊สใดที่มนุษย์หายใจออกเป็นของเสีย และพืชรับเข้าไปเพื่อการสังเคราะห์แสง", choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], choicesTh: ["คาร์บอนไดออกไซด์", "ออกซิเจน", "ไนโตรเจน", "ฮีเลียม"], correct: 0 },
      { q: "Which lightweight gas is commonly used to fill party balloons and blimps because it's much lighter than air?", qTh: "แก๊สน้ำหนักเบาชนิดใดมักถูกใช้เติมลูกโป่งงานปาร์ตี้และเรือเหาะ เพราะเบากว่าอากาศมาก", choices: ["Helium", "Neon", "Hydrogen", "Argon"], choicesTh: ["ฮีเลียม", "นีออน", "ไฮโดรเจน", "อาร์กอน"], correct: 0 },
      { q: "Which gas is often used to fill glowing signs because it produces a bright reddish-orange light?", qTh: "แก๊สใดมักถูกใช้เติมป้ายไฟเรืองแสง เพราะให้แสงสีส้มแดงสว่าง", choices: ["Neon", "Helium", "Argon", "Krypton"], choicesTh: ["นีออน", "ฮีเลียม", "อาร์กอน", "คริปทอน"], correct: 0 },
      { q: "Which lightweight metal is commonly used to make soda cans and kitchen foil?", qTh: "โลหะน้ำหนักเบาชนิดใดมักถูกใช้ทำกระป๋องน้ำอัดลมและฟอยล์ในครัว", choices: ["Aluminum", "Iron", "Lead", "Tin"], choicesTh: ["อะลูมิเนียม", "เหล็ก", "ตะกั่ว", "ดีบุก"], correct: 0 },
      { q: "Which metal is a great conductor of electricity and is commonly used in electrical wiring?", qTh: "โลหะใดนำไฟฟ้าได้ดีเยี่ยม และมักถูกใช้ทำสายไฟ", choices: ["Copper", "Iron", "Lead", "Tin"], choicesTh: ["ทองแดง", "เหล็ก", "ตะกั่ว", "ดีบุก"], correct: 0 },
      { q: "Which of these best describes a metal's typical physical properties?", qTh: "ข้อใดอธิบายสมบัติทางกายภาพทั่วไปของโลหะได้ดีที่สุด", choices: ["Shiny, good conductor of heat and electricity, malleable", "Dull, brittle, poor conductor", "Colorless gas at room temperature", "Always liquid at room temperature"], choicesTh: ["เป็นเงา นำความร้อนและไฟฟ้าได้ดี ตีเป็นแผ่นได้", "หมองคล้ำ เปราะ นำไฟฟ้าได้ไม่ดี", "เป็นแก๊สไม่มีสีที่อุณหภูมิห้อง", "เป็นของเหลวเสมอที่อุณหภูมิห้อง"], correct: 0 },
      { q: "Which term describes elements that are typically dull, brittle when solid, and poor conductors of electricity?", qTh: "คำใดใช้อธิบายธาตุที่โดยทั่วไปหมองคล้ำ เปราะเมื่อเป็นของแข็ง และนำไฟฟ้าได้ไม่ดี", choices: ["Nonmetals", "Metals", "Metalloids", "Noble gases"], choicesTh: ["อโลหะ", "โลหะ", "ธาตุกึ่งโลหะ", "แก๊สมีตระกูล"], correct: 0 },
      { q: "What do we call the property of a metal that lets it be hammered or rolled into thin sheets without breaking?", qTh: "สมบัติของโลหะที่ทำให้สามารถตีหรือรีดให้เป็นแผ่นบางได้โดยไม่แตกหักเรียกว่าอะไร", choices: ["Malleability", "Density", "Conductivity", "Reactivity"], choicesTh: ["ความสามารถในการตีเป็นแผ่น", "ความหนาแน่น", "ความสามารถในการนำไฟฟ้า", "ความว่องไวต่อปฏิกิริยา"], correct: 0 },
      { q: "Which of these elements is well known for not reacting easily, which is why it's used for jewelry and doesn't tarnish?", qTh: "ธาตุใดต่อไปนี้ขึ้นชื่อเรื่องไม่ทำปฏิกิริยาง่าย จึงถูกนำไปใช้ทำเครื่องประดับและไม่หมองคล้ำ", choices: ["Gold", "Sodium", "Potassium", "Lithium"], choicesTh: ["ทองคำ", "โซเดียม", "โพแทสเซียม", "ลิเธียม"], correct: 0 },
      { q: "Rust forms when iron reacts with which gas in the air?", qTh: "สนิมเกิดขึ้นเมื่อเหล็กทำปฏิกิริยากับแก๊สใดในอากาศ", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], choicesTh: ["ออกซิเจน", "ไนโตรเจน", "คาร์บอนไดออกไซด์", "ฮีเลียม"], correct: 0 },
      { q: "Which state of matter has both a definite shape and a definite volume?", qTh: "สถานะของสสารใดมีทั้งรูปร่างที่แน่นอนและปริมาตรที่แน่นอน", choices: ["Solid", "Liquid", "Gas", "Plasma"], choicesTh: ["ของแข็ง", "ของเหลว", "แก๊ส", "พลาสมา"], correct: 0 }
];

// 3 quiz questions for each element, numbers 1-59.
export const ELEMENT_QUIZZES = {
      1: { name: "Hydrogen", questions: [
        { q: "What is the chemical symbol for hydrogen?", qTh: "สัญลักษณ์ทางเคมีของไฮโดรเจนคืออะไร", choices: ["H", "He", "Hy", "Hd"], choicesTh: ["H", "He", "Hy", "Hd"], correct: 0 },
        { q: "What is the most abundant element in the entire universe?", qTh: "ธาตุใดมีมากที่สุดในเอกภพทั้งหมด", choices: ["Hydrogen", "Helium", "Oxygen", "Carbon"], choicesTh: ["ไฮโดรเจน", "ฮีเลียม", "ออกซิเจน", "คาร์บอน"], correct: 0 },
        { q: "Hydrogen atoms fuse together in the Sun's core to release energy. What element do they form?", qTh: "อะตอมไฮโดรเจนหลอมรวมกันในแกนกลางดวงอาทิตย์เพื่อปลดปล่อยพลังงาน พวกมันรวมกันเป็นธาตุใด", choices: ["Helium", "Carbon", "Oxygen", "Neon"], choicesTh: ["ฮีเลียม", "คาร์บอน", "ออกซิเจน", "นีออน"], correct: 0 }
      ]},
      2: { name: "Helium", questions: [
        { q: "What is the chemical symbol for helium?", qTh: "สัญลักษณ์ทางเคมีของฮีเลียมคืออะไร", choices: ["He", "H", "Hl", "Hu"], choicesTh: ["He", "H", "Hl", "Hu"], correct: 0 },
        { q: "Why is helium used to fill party balloons and blimps?", qTh: "เหตุใดฮีเลียมจึงถูกใช้เติมลูกโป่งงานปาร์ตี้และเรือเหาะ", choices: ["It's lighter than air and doesn't burn", "It's the heaviest gas", "It's magnetic", "It glows in the dark"], choicesTh: ["มันเบากว่าอากาศและไม่ติดไฟ", "มันเป็นแก๊สที่หนักที่สุด", "มันมีแม่เหล็ก", "มันเรืองแสงในที่มืด"], correct: 0 },
        { q: "Helium belongs to which family of elements that barely react with anything?", qTh: "ฮีเลียมอยู่ในตระกูลธาตุใดที่แทบไม่ทำปฏิกิริยากับสิ่งใดเลย", choices: ["Noble gases", "Alkali metals", "Halogens", "Metalloids"], choicesTh: ["แก๊สมีตระกูล", "โลหะแอลคาไล", "ธาตุแฮโลเจน", "ธาตุกึ่งโลหะ"], correct: 0 }
      ]},
      3: { name: "Lithium", questions: [
        { q: "What is the chemical symbol for lithium?", qTh: "สัญลักษณ์ทางเคมีของลิเธียมคืออะไร", choices: ["Li", "Lt", "Ln", "Lu"], choicesTh: ["Li", "Lt", "Ln", "Lu"], correct: 0 },
        { q: "Lithium is best known today for being used in what?", qTh: "ปัจจุบันลิเธียมเป็นที่รู้จักมากที่สุดจากการถูกนำไปใช้ในอะไร", choices: ["Rechargeable batteries", "Light bulbs", "Window glass", "Rubber tires"], choicesTh: ["แบตเตอรี่แบบชาร์จไฟได้", "หลอดไฟ", "กระจกหน้าต่าง", "ยางรถยนต์"], correct: 0 },
        { q: "What stands out about lithium compared to all other metals?", qTh: "อะไรที่โดดเด่นเกี่ยวกับลิเธียมเมื่อเทียบกับโลหะอื่นทั้งหมด", choices: ["It's the lightest metal on the periodic table", "It's the heaviest metal", "It's a liquid at room temperature", "It doesn't conduct electricity"], choicesTh: ["มันเป็นโลหะที่เบาที่สุดในตารางธาตุ", "มันเป็นโลหะที่หนักที่สุด", "มันเป็นของเหลวที่อุณหภูมิห้อง", "มันไม่นำไฟฟ้า"], correct: 0 }
      ]},
      4: { name: "Beryllium", questions: [
        { q: "What is the chemical symbol for beryllium?", qTh: "สัญลักษณ์ทางเคมีของเบริลเลียมคืออะไร", choices: ["Be", "Br", "By", "Bl"], choicesTh: ["Be", "Br", "By", "Bl"], correct: 0 },
        { q: "Beryllium is prized in aerospace and X-ray equipment because it's...", qTh: "เบริลเลียมเป็นที่ต้องการในอุตสาหกรรมการบินและอุปกรณ์เอกซเรย์เพราะมันเป็นอย่างไร", choices: ["Lightweight, strong, and lets X-rays pass through", "Extremely heavy and dense", "A liquid at room temperature", "Radioactive"], choicesTh: ["น้ำหนักเบา แข็งแรง และยอมให้รังสีเอกซ์ผ่านได้", "หนักและหนาแน่นมาก", "เป็นของเหลวที่อุณหภูมิห้อง", "มีกัมมันตรังสี"], correct: 0 },
        { q: "Beryllium belongs to which group of the periodic table?", qTh: "เบริลเลียมอยู่ในหมู่ใดของตารางธาตุ", choices: ["Alkaline earth metals", "Alkali metals", "Halogens", "Noble gases"], choicesTh: ["โลหะแอลคาไลน์เอิร์ท", "โลหะแอลคาไล", "ธาตุแฮโลเจน", "แก๊สมีตระกูล"], correct: 0 }
      ]},
      5: { name: "Boron", questions: [
        { q: "What is the chemical symbol for boron?", qTh: "สัญลักษณ์ทางเคมีของโบรอนคืออะไร", choices: ["B", "Bo", "Br", "Bn"], choicesTh: ["B", "Bo", "Br", "Bn"], correct: 0 },
        { q: "Boron is added to glass to make it more resistant to heat, as in what popular cookware brand?", qTh: "โบรอนถูกเติมลงในแก้วเพื่อให้ทนความร้อนมากขึ้น เช่นในแบรนด์เครื่องครัวยอดนิยมใด", choices: ["Pyrex", "Tupperware", "Corelle", "Le Creuset"], choicesTh: ["Pyrex", "Tupperware", "Corelle", "Le Creuset"], correct: 0 },
        { q: "Boron is classified as what kind of element, having properties of both metals and nonmetals?", qTh: "โบรอนถูกจัดเป็นธาตุประเภทใด ซึ่งมีสมบัติทั้งของโลหะและอโลหะ", choices: ["A metalloid", "An alkali metal", "A noble gas", "A halogen"], choicesTh: ["ธาตุกึ่งโลหะ", "โลหะแอลคาไล", "แก๊สมีตระกูล", "ธาตุแฮโลเจน"], correct: 0 }
      ]},
      6: { name: "Carbon", questions: [
        { q: "What is the chemical symbol for carbon?", qTh: "สัญลักษณ์ทางเคมีของคาร์บอนคืออะไร", choices: ["C", "Ca", "Co", "Cr"], choicesTh: ["C", "Ca", "Co", "Cr"], correct: 0 },
        { q: "What is carbon the basis of, since it can bond into so many different chains and rings?", qTh: "คาร์บอนเป็นพื้นฐานของสิ่งใด เนื่องจากสามารถสร้างพันธะเป็นสายโซ่และวงแหวนที่หลากหลายได้", choices: ["All known life on Earth", "The Earth's atmosphere", "Ocean water", "Sunlight"], choicesTh: ["สิ่งมีชีวิตทั้งหมดที่รู้จักบนโลก", "บรรยากาศของโลก", "น้ำทะเล", "แสงอาทิตย์"], correct: 0 },
        { q: "Diamond and graphite (pencil lead) are both made of pure carbon. What do we call different structural forms of the same element?", qTh: "เพชรและแกรไฟต์ (ไส้ดินสอ) ทั้งคู่ทำจากคาร์บอนบริสุทธิ์ เราเรียกรูปแบบโครงสร้างที่แตกต่างกันของธาตุเดียวกันว่าอะไร", choices: ["Allotropes", "Isotopes", "Isomers", "Alloys"], choicesTh: ["อัญรูป", "ไอโซโทป", "ไอโซเมอร์", "โลหะผสม"], correct: 0 }
      ]},
      7: { name: "Nitrogen", questions: [
        { q: "What is the chemical symbol for nitrogen?", qTh: "สัญลักษณ์ทางเคมีของไนโตรเจนคืออะไร", choices: ["N", "Ni", "No", "Na"], choicesTh: ["N", "Ni", "No", "Na"], correct: 0 },
        { q: "About what percentage of Earth's atmosphere is nitrogen?", qTh: "ไนโตรเจนคิดเป็นประมาณกี่เปอร์เซ็นต์ของบรรยากาศโลก", choices: ["78%", "21%", "50%", "1%"], choicesTh: ["78%", "21%", "50%", "1%"], correct: 0 },
        { q: "Liquid nitrogen is extremely cold and is often used to do what?", qTh: "ไนโตรเจนเหลวเย็นจัดมาก และมักถูกใช้ทำอะไร", choices: ["Quickly freeze things", "Heat things", "Dissolve metal", "Power car engines"], choicesTh: ["แช่แข็งสิ่งของอย่างรวดเร็ว", "ให้ความร้อนแก่สิ่งของ", "ละลายโลหะ", "ขับเคลื่อนเครื่องยนต์รถยนต์"], correct: 0 }
      ]},
      8: { name: "Oxygen", questions: [
        { q: "What is the chemical symbol for oxygen?", qTh: "สัญลักษณ์ทางเคมีของออกซิเจนคืออะไร", choices: ["O", "Ox", "Og", "Om"], choicesTh: ["O", "Ox", "Og", "Om"], correct: 0 },
        { q: "About what percentage of Earth's atmosphere is oxygen?", qTh: "ออกซิเจนคิดเป็นประมาณกี่เปอร์เซ็นต์ของบรรยากาศโลก", choices: ["21%", "78%", "50%", "5%"], choicesTh: ["21%", "78%", "50%", "5%"], correct: 0 },
        { q: "Besides breathing, what else does oxygen make possible?", qTh: "นอกจากการหายใจแล้ว ออกซิเจนยังทำให้สิ่งใดเกิดขึ้นได้อีก", choices: ["Fire (combustion)", "Photosynthesis by itself", "Magnetism", "Radioactivity"], choicesTh: ["ไฟ (การเผาไหม้)", "การสังเคราะห์แสงด้วยตัวเอง", "แม่เหล็ก", "กัมมันตรังสี"], correct: 0 }
      ]},
      9: { name: "Fluorine", questions: [
        { q: "What is the chemical symbol for fluorine?", qTh: "สัญลักษณ์ทางเคมีของฟลูออรีนคืออะไร", choices: ["F", "Fl", "Fr", "Fn"], choicesTh: ["F", "Fl", "Fr", "Fn"], correct: 0 },
        { q: "Fluorine compounds are added to toothpaste and drinking water to help with what?", qTh: "สารประกอบฟลูออรีนถูกเติมลงในยาสีฟันและน้ำดื่มเพื่อช่วยเรื่องใด", choices: ["Preventing tooth decay", "Killing bacteria in food", "Coloring water blue", "Softening water"], choicesTh: ["ป้องกันฟันผุ", "ฆ่าเชื้อแบคทีเรียในอาหาร", "ทำให้น้ำเป็นสีฟ้า", "ทำให้น้ำอ่อนตัว"], correct: 0 },
        { q: "Fluorine is known as the most reactive of all elements. What family does it belong to?", qTh: "ฟลูออรีนขึ้นชื่อว่าเป็นธาตุที่ว่องไวต่อปฏิกิริยามากที่สุดในบรรดาธาตุทั้งหมด มันอยู่ในตระกูลใด", choices: ["Halogens", "Noble gases", "Alkali metals", "Alkaline earth metals"], choicesTh: ["ธาตุแฮโลเจน", "แก๊สมีตระกูล", "โลหะแอลคาไล", "โลหะแอลคาไลน์เอิร์ท"], correct: 0 }
      ]},
      10: { name: "Neon", questions: [
        { q: "What is the chemical symbol for neon?", qTh: "สัญลักษณ์ทางเคมีของนีออนคืออะไร", choices: ["Ne", "No", "N", "Nn"], choicesTh: ["Ne", "No", "N", "Nn"], correct: 0 },
        { q: "Neon is famous for glowing reddish-orange when electrified, which is why it's used in what?", qTh: "นีออนขึ้นชื่อเรื่องการเรืองแสงสีส้มแดงเมื่อมีกระแสไฟฟ้าไหลผ่าน จึงถูกนำไปใช้ทำอะไร", choices: ["Neon signs", "Batteries", "Fireworks", "Light bulbs' filaments"], choicesTh: ["ป้ายไฟนีออน", "แบตเตอรี่", "ดอกไม้ไฟ", "ไส้หลอดไฟ"], correct: 0 },
        { q: "Like helium, neon belongs to which group of elements that rarely react?", qTh: "เช่นเดียวกับฮีเลียม นีออนอยู่ในกลุ่มธาตุใดที่แทบไม่ทำปฏิกิริยา", choices: ["Noble gases", "Halogens", "Alkali metals", "Transition metals"], choicesTh: ["แก๊สมีตระกูล", "ธาตุแฮโลเจน", "โลหะแอลคาไล", "โลหะทรานซิชัน"], correct: 0 }
      ]},
      11: { name: "Sodium", questions: [
        { q: "What is the chemical symbol for sodium?", qTh: "สัญลักษณ์ทางเคมีของโซเดียมคืออะไร", choices: ["Na", "So", "Sd", "Sn"], choicesTh: ["Na", "So", "Sd", "Sn"], correct: 0 },
        { q: "Sodium is one of the two elements that make up common table salt. What is the other?", qTh: "โซเดียมเป็นหนึ่งในสองธาตุที่ประกอบกันเป็นเกลือแกงทั่วไป อีกธาตุหนึ่งคืออะไร", choices: ["Chlorine", "Oxygen", "Nitrogen", "Sulfur"], choicesTh: ["คลอรีน", "ออกซิเจน", "ไนโตรเจน", "กำมะถัน"], correct: 0 },
        { q: "What happens when you drop a piece of sodium metal into water?", qTh: "จะเกิดอะไรขึ้นเมื่อหย่อนโซเดียมโลหะลงในน้ำ", choices: ["It reacts violently", "Nothing happens", "It turns into ice", "It dissolves slowly and quietly"], choicesTh: ["มันทำปฏิกิริยาอย่างรุนแรง", "ไม่มีอะไรเกิดขึ้น", "มันกลายเป็นน้ำแข็ง", "มันละลายอย่างช้าๆ และเงียบๆ"], correct: 0 }
      ]},
      12: { name: "Magnesium", questions: [
        { q: "What is the chemical symbol for magnesium?", qTh: "สัญลักษณ์ทางเคมีของแมกนีเซียมคืออะไร", choices: ["Mg", "Ma", "Mn", "Mo"], choicesTh: ["Mg", "Ma", "Mn", "Mo"], correct: 0 },
        { q: "Magnesium metal burns with a very bright white light, which is why it's used in...", qTh: "แมกนีเซียมโลหะเผาไหม้ให้แสงสีขาวที่สว่างมาก จึงถูกนำไปใช้ในอะไร", choices: ["Fireworks and flares", "Window glass", "Rubber tires", "Refrigerators"], choicesTh: ["ดอกไม้ไฟและพลุสัญญาณ", "กระจกหน้าต่าง", "ยางรถยนต์", "ตู้เย็น"], correct: 0 },
        { q: "Magnesium is a lightweight metal often alloyed for use in what kind of products?", qTh: "แมกนีเซียมเป็นโลหะน้ำหนักเบาที่มักถูกนำไปผสมเป็นโลหะผสมเพื่อใช้ในผลิตภัณฑ์ประเภทใด", choices: ["Phone and laptop cases", "Glass bottles", "Rubber tires", "Concrete"], choicesTh: ["เคสโทรศัพท์และแล็ปท็อป", "ขวดแก้ว", "ยางรถยนต์", "คอนกรีต"], correct: 0 }
      ]},
      13: { name: "Aluminium", questions: [
        { q: "What is the chemical symbol for aluminium?", qTh: "สัญลักษณ์ทางเคมีของอะลูมิเนียมคืออะไร", choices: ["Al", "Am", "An", "Au"], choicesTh: ["Al", "Am", "An", "Au"], correct: 0 },
        { q: "Aluminium is lightweight and doesn't rust easily, which is why it's used to make...", qTh: "อะลูมิเนียมมีน้ำหนักเบาและไม่ค่อยเป็นสนิม จึงถูกนำไปใช้ทำอะไร", choices: ["Soda cans and kitchen foil", "Steel beams", "Glass windows", "Rubber tires"], choicesTh: ["กระป๋องน้ำอัดลมและฟอยล์ในครัว", "คานเหล็ก", "กระจกหน้าต่าง", "ยางรถยนต์"], correct: 0 },
        { q: "Aluminium holds what title among metals found in the Earth's crust?", qTh: "อะลูมิเนียมครองตำแหน่งใดในบรรดาโลหะที่พบในเปลือกโลก", choices: ["The most abundant metal", "The rarest metal", "The heaviest metal", "The only liquid metal"], choicesTh: ["โลหะที่มีมากที่สุด", "โลหะที่หายากที่สุด", "โลหะที่หนักที่สุด", "โลหะชนิดเดียวที่เป็นของเหลว"], correct: 0 }
      ]},
      14: { name: "Silicon", questions: [
        { q: "What is the chemical symbol for silicon?", qTh: "สัญลักษณ์ทางเคมีของซิลิคอนคืออะไร", choices: ["Si", "Sl", "Sc", "Sn"], choicesTh: ["Si", "Sl", "Sc", "Sn"], correct: 0 },
        { q: "Silicon is the key material used to make what everyday technology?", qTh: "ซิลิคอนเป็นวัสดุสำคัญที่ใช้ทำเทคโนโลยีใดที่พบเห็นในชีวิตประจำวัน", choices: ["Computer chips", "Copper wire", "Steel beams", "Aluminum foil"], choicesTh: ["ชิปคอมพิวเตอร์", "สายไฟทองแดง", "คานเหล็ก", "ฟอยล์อะลูมิเนียม"], correct: 0 },
        { q: "Silicon, which has properties of both metals and nonmetals, is found in large amounts in...", qTh: "ซิลิคอน ซึ่งมีสมบัติทั้งของโลหะและอโลหะ พบได้ในปริมาณมากในสิ่งใด", choices: ["Sand", "Ocean water", "The atmosphere", "Wood"], choicesTh: ["ทราย", "น้ำทะเล", "บรรยากาศ", "ไม้"], correct: 0 }
      ]},
      15: { name: "Phosphorus", questions: [
        { q: "What is the chemical symbol for phosphorus?", qTh: "สัญลักษณ์ทางเคมีของฟอสฟอรัสคืออะไร", choices: ["P", "Ph", "Po", "Pr"], choicesTh: ["P", "Ph", "Po", "Pr"], correct: 0 },
        { q: "Along with calcium, phosphorus is a key ingredient in what parts of the body?", qTh: "ฟอสฟอรัสร่วมกับแคลเซียมเป็นส่วนประกอบสำคัญของส่วนใดในร่างกาย", choices: ["Bones and teeth", "Blood", "Skin", "Hair"], choicesTh: ["กระดูกและฟัน", "เลือด", "ผิวหนัง", "เส้นผม"], correct: 0 },
        { q: "Phosphorus ignites so easily that it's used to make the striking tips of what everyday item?", qTh: "ฟอสฟอรัสติดไฟได้ง่ายมากจนถูกนำไปใช้ทำหัวจุดไฟของสิ่งของในชีวิตประจำวันชนิดใด", choices: ["Matches", "Batteries", "Light bulbs", "Pencils"], choicesTh: ["ไม้ขีดไฟ", "แบตเตอรี่", "หลอดไฟ", "ดินสอ"], correct: 0 }
      ]},
      16: { name: "Sulfur", questions: [
        { q: "What is the chemical symbol for sulfur?", qTh: "สัญลักษณ์ทางเคมีของกำมะถันคืออะไร", choices: ["S", "Su", "Sl", "Sf"], choicesTh: ["S", "Su", "Sl", "Sf"], correct: 0 },
        { q: "Sulfur compounds like hydrogen sulfide are infamous for smelling like...", qTh: "สารประกอบกำมะถันอย่างไฮโดรเจนซัลไฟด์ขึ้นชื่อเรื่องกลิ่นเหมือนอะไร", choices: ["Rotten eggs", "Fresh flowers", "Burnt toast", "Vinegar"], choicesTh: ["ไข่เน่า", "ดอกไม้สด", "ขนมปังไหม้", "น้ำส้มสายชู"], correct: 0 },
        { q: "Sulfur is used to \"vulcanize\" rubber, a process that does what to rubber?", qTh: "กำมะถันถูกใช้ในกระบวนการ \"วัลคาไนซ์\" ยาง ซึ่งเป็นกระบวนการที่ทำอะไรกับยาง", choices: ["Makes it stronger and more durable", "Makes it melt faster", "Turns it into a liquid", "Makes it transparent"], choicesTh: ["ทำให้แข็งแรงและทนทานขึ้น", "ทำให้ละลายเร็วขึ้น", "ทำให้กลายเป็นของเหลว", "ทำให้โปร่งใส"], correct: 0 }
      ]},
      17: { name: "Chlorine", questions: [
        { q: "What is the chemical symbol for chlorine?", qTh: "สัญลักษณ์ทางเคมีของคลอรีนคืออะไร", choices: ["Cl", "Ch", "Co", "Cr"], choicesTh: ["Cl", "Ch", "Co", "Cr"], correct: 0 },
        { q: "Chlorine is commonly added to swimming pools and drinking water to do what?", qTh: "คลอรีนมักถูกเติมลงในสระว่ายน้ำและน้ำดื่มเพื่อทำอะไร", choices: ["Disinfect and kill germs", "Add flavor", "Make water blue", "Soften the water"], choicesTh: ["ฆ่าเชื้อโรคและกำจัดเชื้อแบคทีเรีย", "เพิ่มรสชาติ", "ทำให้น้ำเป็นสีฟ้า", "ทำให้น้ำอ่อนตัว"], correct: 0 },
        { q: "Chlorine is part of which reactive group of nonmetals?", qTh: "คลอรีนอยู่ในกลุ่มอโลหะที่ว่องไวต่อปฏิกิริยากลุ่มใด", choices: ["Halogens", "Noble gases", "Alkali metals", "Transition metals"], choicesTh: ["ธาตุแฮโลเจน", "แก๊สมีตระกูล", "โลหะแอลคาไล", "โลหะทรานซิชัน"], correct: 0 }
      ]},
      18: { name: "Argon", questions: [
        { q: "What is the chemical symbol for argon?", qTh: "สัญลักษณ์ทางเคมีของอาร์กอนคืออะไร", choices: ["Ar", "Ag", "Au", "An"], choicesTh: ["Ar", "Ag", "Au", "An"], correct: 0 },
        { q: "Argon gas is used to fill light bulbs to stop the filament from doing what?", qTh: "แก๊สอาร์กอนถูกใช้เติมในหลอดไฟเพื่อป้องกันไม่ให้ไส้หลอดทำอะไร", choices: ["Burning up too quickly", "Glowing too brightly", "Turning blue", "Melting the glass"], choicesTh: ["ไหม้เร็วเกินไป", "เรืองแสงสว่างเกินไป", "เปลี่ยนเป็นสีฟ้า", "ทำให้กระจกละลาย"], correct: 0 },
        { q: "Argon makes up close to 1% of Earth's atmosphere, making it a member of which gas family?", qTh: "อาร์กอนคิดเป็นเกือบ 1% ของบรรยากาศโลก ทำให้มันเป็นสมาชิกของตระกูลแก๊สใด", choices: ["Noble gases", "Halogens", "Alkali metals", "Alkaline earth metals"], choicesTh: ["แก๊สมีตระกูล", "ธาตุแฮโลเจน", "โลหะแอลคาไล", "โลหะแอลคาไลน์เอิร์ท"], correct: 0 }
      ]},
      19: { name: "Potassium", questions: [
        { q: "What is the chemical symbol for potassium?", qTh: "สัญลักษณ์ทางเคมีของโพแทสเซียมคืออะไร", choices: ["K", "Po", "Pt", "Ps"], choicesTh: ["K", "Po", "Pt", "Ps"], correct: 0 },
        { q: "Potassium is important for muscle and nerve function and is famously found in what fruit?", qTh: "โพแทสเซียมสำคัญต่อการทำงานของกล้ามเนื้อและระบบประสาท และเป็นที่รู้จักว่าพบมากในผลไม้ชนิดใด", choices: ["Bananas", "Apples", "Oranges", "Grapes"], choicesTh: ["กล้วย", "แอปเปิล", "ส้ม", "องุ่น"], correct: 0 },
        { q: "Like sodium, potassium is an alkali metal that reacts how with water?", qTh: "เช่นเดียวกับโซเดียม โพแทสเซียมเป็นโลหะแอลคาไลที่ทำปฏิกิริยากับน้ำอย่างไร", choices: ["Violently", "Not at all", "Very slowly over years", "Only when frozen"], choicesTh: ["อย่างรุนแรง", "ไม่ทำปฏิกิริยาเลย", "อย่างช้ามากเป็นเวลาหลายปี", "ทำปฏิกิริยาเมื่อแช่แข็งเท่านั้น"], correct: 0 }
      ]},
      20: { name: "Calcium", questions: [
        { q: "What is the chemical symbol for calcium?", qTh: "สัญลักษณ์ทางเคมีของแคลเซียมคืออะไร", choices: ["Ca", "Cl", "Co", "Cm"], choicesTh: ["Ca", "Cl", "Co", "Cm"], correct: 0 },
        { q: "Calcium is essential for building strong bones and teeth, and is found in large amounts in...", qTh: "แคลเซียมจำเป็นต่อการสร้างกระดูกและฟันให้แข็งแรง และพบได้ในปริมาณมากในสิ่งใด", choices: ["Milk", "Bread", "Meat", "Rice"], choicesTh: ["นม", "ขนมปัง", "เนื้อสัตว์", "ข้าว"], correct: 0 },
        { q: "Calcium belongs to which group of the periodic table?", qTh: "แคลเซียมอยู่ในหมู่ใดของตารางธาตุ", choices: ["Alkaline earth metals", "Alkali metals", "Halogens", "Noble gases"], choicesTh: ["โลหะแอลคาไลน์เอิร์ท", "โลหะแอลคาไล", "ธาตุแฮโลเจน", "แก๊สมีตระกูล"], correct: 0 }
      ]},
      21: { name: "Scandium", questions: [
        { q: "What is the chemical symbol for scandium?", qTh: "สัญลักษณ์ทางเคมีของสแกนเดียมคืออะไร", choices: ["Sc", "Sd", "Sn", "Sm"], choicesTh: ["Sc", "Sd", "Sn", "Sm"], correct: 0 },
        { q: "Scandium alloys are prized in aerospace parts and sports equipment for being...", qTh: "โลหะผสมสแกนเดียมเป็นที่ต้องการในชิ้นส่วนอากาศยานและอุปกรณ์กีฬาเพราะเป็นอย่างไร", choices: ["Strong yet lightweight", "Extremely heavy", "Liquid at room temperature", "Radioactive"], choicesTh: ["แข็งแรงแต่มีน้ำหนักเบา", "หนักมาก", "เป็นของเหลวที่อุณหภูมิห้อง", "มีกัมมันตรังสี"], correct: 0 },
        { q: "Scandium is classified as what kind of metal on the periodic table?", qTh: "สแกนเดียมถูกจัดเป็นโลหะประเภทใดในตารางธาตุ", choices: ["A transition metal", "An alkali metal", "A noble gas", "A halogen"], choicesTh: ["โลหะทรานซิชัน", "โลหะแอลคาไล", "แก๊สมีตระกูล", "ธาตุแฮโลเจน"], correct: 0 }
      ]},
      22: { name: "Titanium", questions: [
        { q: "What is the chemical symbol for titanium?", qTh: "สัญลักษณ์ทางเคมีของไทเทเนียมคืออะไร", choices: ["Ti", "Ta", "Tn", "To"], choicesTh: ["Ti", "Ta", "Tn", "To"], correct: 0 },
        { q: "Titanium is strong, lightweight, and resists corrosion, which is why it's used in jet engines and...", qTh: "ไทเทเนียมแข็งแรง น้ำหนักเบา และทนต่อการกัดกร่อน จึงถูกใช้ในเครื่องยนต์เจ็ตและอะไร", choices: ["Artificial hip and joint replacements", "Rubber tires", "Window glass", "Batteries"], choicesTh: ["ข้อสะโพกและข้อต่อเทียม", "ยางรถยนต์", "กระจกหน้าต่าง", "แบตเตอรี่"], correct: 0 },
        { q: "What kind of element is titanium?", qTh: "ไทเทเนียมเป็นธาตุประเภทใด", choices: ["A transition metal", "A noble gas", "An alkali metal", "A metalloid"], choicesTh: ["โลหะทรานซิชัน", "แก๊สมีตระกูล", "โลหะแอลคาไล", "ธาตุกึ่งโลหะ"], correct: 0 }
      ]},
      23: { name: "Vanadium", questions: [
        { q: "What is the chemical symbol for vanadium?", qTh: "สัญลักษณ์ทางเคมีของวาเนเดียมคืออะไร", choices: ["V", "Va", "Vn", "Vd"], choicesTh: ["V", "Va", "Vn", "Vd"], correct: 0 },
        { q: "Vanadium is often added to steel to make tools and construction materials...", qTh: "วาเนเดียมมักถูกเติมลงในเหล็กกล้าเพื่อทำให้เครื่องมือและวัสดุก่อสร้างเป็นอย่างไร", choices: ["Stronger", "Lighter in color", "More flexible like rubber", "Transparent"], choicesTh: ["แข็งแรงขึ้น", "มีสีอ่อนลง", "ยืดหยุ่นเหมือนยางมากขึ้น", "โปร่งใส"], correct: 0 },
        { q: "What kind of element is vanadium?", qTh: "วาเนเดียมเป็นธาตุประเภทใด", choices: ["A transition metal", "A halogen", "A noble gas", "An alkali metal"], choicesTh: ["โลหะทรานซิชัน", "ธาตุแฮโลเจน", "แก๊สมีตระกูล", "โลหะแอลคาไล"], correct: 0 }
      ]},
      24: { name: "Chromium", questions: [
        { q: "What is the chemical symbol for chromium?", qTh: "สัญลักษณ์ทางเคมีของโครเมียมคืออะไร", choices: ["Cr", "Ch", "Co", "Cm"], choicesTh: ["Cr", "Ch", "Co", "Cm"], correct: 0 },
        { q: "Chromium is used to make stainless steel and the shiny finish known as...", qTh: "โครเมียมถูกใช้ทำสเตนเลสและผิวเคลือบเงาวาวที่รู้จักกันในชื่อใด", choices: ["Chrome plating", "Galvanizing", "Tempering", "Anodizing"], choicesTh: ["การชุบโครเมียม", "การชุบสังกะสี", "การอบชุบ", "การอโนไดซ์"], correct: 0 },
        { q: "Chromium compounds give some gemstones, like rubies and emeralds, their...", qTh: "สารประกอบโครเมียมทำให้อัญมณีบางชนิด เช่น ทับทิมและมรกต มีอะไร", choices: ["Vivid color", "Hardness", "Weight", "Transparency"], choicesTh: ["สีสันสดใส", "ความแข็ง", "น้ำหนัก", "ความโปร่งใส"], correct: 0 }
      ]},
      25: { name: "Manganese", questions: [
        { q: "What is the chemical symbol for manganese?", qTh: "สัญลักษณ์ทางเคมีของแมงกานีสคืออะไร", choices: ["Mn", "Mg", "Ma", "Mo"], choicesTh: ["Mn", "Mg", "Ma", "Mo"], correct: 0 },
        { q: "Manganese is added to steel to make it stronger and more resistant to...", qTh: "แมงกานีสถูกเติมลงในเหล็กกล้าเพื่อทำให้แข็งแรงขึ้นและทนทานต่อสิ่งใดมากขึ้น", choices: ["Wear", "Melting", "Rusting alone", "Electricity"], choicesTh: ["การสึกหรอ", "การหลอมละลาย", "การเกิดสนิมเพียงอย่างเดียว", "ไฟฟ้า"], correct: 0 },
        { q: "What kind of element is manganese?", qTh: "แมงกานีสเป็นธาตุประเภทใด", choices: ["A transition metal", "A halogen", "A noble gas", "An alkali metal"], choicesTh: ["โลหะทรานซิชัน", "ธาตุแฮโลเจน", "แก๊สมีตระกูล", "โลหะแอลคาไล"], correct: 0 }
      ]},
      26: { name: "Iron", questions: [
        { q: "What is the chemical symbol for iron?", qTh: "สัญลักษณ์ทางเคมีของเหล็กคืออะไร", choices: ["Fe", "Ir", "In", "I"], choicesTh: ["Fe", "Ir", "In", "I"], correct: 0 },
        { q: "Iron gives blood its red color and helps it do what?", qTh: "เหล็กทำให้เลือดมีสีแดงและช่วยให้เลือดทำอะไร", choices: ["Carry oxygen", "Fight infections", "Clot faster", "Regulate temperature"], choicesTh: ["ลำเลียงออกซิเจน", "ต่อสู้กับการติดเชื้อ", "แข็งตัวเร็วขึ้น", "ควบคุมอุณหภูมิ"], correct: 0 },
        { q: "Iron is the main ingredient in what widely-used building material?", qTh: "เหล็กเป็นส่วนประกอบหลักของวัสดุก่อสร้างที่ใช้กันอย่างแพร่หลายชนิดใด", choices: ["Steel", "Glass", "Concrete", "Rubber"], choicesTh: ["เหล็กกล้า", "กระจก", "คอนกรีต", "ยาง"], correct: 0 }
      ]},
      27: { name: "Cobalt", questions: [
        { q: "What is the chemical symbol for cobalt?", qTh: "สัญลักษณ์ทางเคมีของโคบอลต์คืออะไร", choices: ["Co", "Cb", "Cl", "Ct"], choicesTh: ["Co", "Cb", "Cl", "Ct"], correct: 0 },
        { q: "Cobalt is a key ingredient in what kind of modern technology?", qTh: "โคบอลต์เป็นส่วนประกอบสำคัญของเทคโนโลยีสมัยใหม่ชนิดใด", choices: ["Rechargeable batteries", "Window glass", "Rubber tires", "Paper"], choicesTh: ["แบตเตอรี่แบบชาร์จไฟได้", "กระจกหน้าต่าง", "ยางรถยนต์", "กระดาษ"], correct: 0 },
        { q: "Cobalt compounds have long been used to make glass and pigments a deep...", qTh: "สารประกอบโคบอลต์ถูกใช้มายาวนานเพื่อทำให้แก้วและเม็ดสีมีสีเข้มแบบใด", choices: ["Blue", "Red", "Green", "Yellow"], choicesTh: ["น้ำเงิน", "แดง", "เขียว", "เหลือง"], correct: 0 }
      ]},
      28: { name: "Nickel", questions: [
        { q: "What is the chemical symbol for nickel?", qTh: "สัญลักษณ์ทางเคมีของนิกเกิลคืออะไร", choices: ["Ni", "Nk", "Nc", "Ne"], choicesTh: ["Ni", "Nk", "Nc", "Ne"], correct: 0 },
        { q: "The US five-cent coin is nicknamed after which element it's partly made of?", qTh: "เหรียญห้าเซนต์ของสหรัฐฯ ถูกเรียกชื่อเล่นตามธาตุใดที่เป็นส่วนประกอบ", choices: ["Nickel", "Copper", "Zinc", "Tin"], choicesTh: ["นิกเกิล", "ทองแดง", "สังกะสี", "ดีบุก"], correct: 0 },
        { q: "Nickel is often combined with iron and chromium to make what corrosion-resistant material?", qTh: "นิกเกิลมักถูกผสมกับเหล็กและโครเมียมเพื่อทำวัสดุทนการกัดกร่อนชนิดใด", choices: ["Stainless steel", "Bronze", "Pewter", "Brass"], choicesTh: ["สเตนเลส", "สำริด", "โลหะผสมดีบุก", "ทองเหลือง"], correct: 0 }
      ]},
      29: { name: "Copper", questions: [
        { q: "What is the chemical symbol for copper?", qTh: "สัญลักษณ์ทางเคมีของทองแดงคืออะไร", choices: ["Cu", "Co", "Cp", "Cr"], choicesTh: ["Cu", "Co", "Cp", "Cr"], correct: 0 },
        { q: "Copper is an excellent conductor of electricity, which is why it's used in...", qTh: "ทองแดงนำไฟฟ้าได้ดีเยี่ยม จึงถูกใช้ในสิ่งใด", choices: ["Electrical wiring", "Window glass", "Rubber tires", "Concrete"], choicesTh: ["สายไฟฟ้า", "กระจกหน้าต่าง", "ยางรถยนต์", "คอนกรีต"], correct: 0 },
        { q: "What color does copper turn as it slowly corrodes, like on the Statue of Liberty?", qTh: "ทองแดงเปลี่ยนเป็นสีใดเมื่อค่อยๆ ผุกร่อน เช่นเดียวกับเทพีเสรีภาพ", choices: ["Green", "Red", "Black", "White"], choicesTh: ["เขียว", "แดง", "ดำ", "ขาว"], correct: 0 }
      ]},
      30: { name: "Zinc", questions: [
        { q: "What is the chemical symbol for zinc?", qTh: "สัญลักษณ์ทางเคมีของสังกะสีคืออะไร", choices: ["Zn", "Zi", "Zc", "Zk"], choicesTh: ["Zn", "Zi", "Zc", "Zk"], correct: 0 },
        { q: "Zinc is coated onto steel in a process called galvanizing to prevent...", qTh: "สังกะสีถูกเคลือบลงบนเหล็กกล้าในกระบวนการที่เรียกว่าการชุบสังกะสีเพื่อป้องกันสิ่งใด", choices: ["Rust", "Melting", "Discoloration", "Cracking"], choicesTh: ["สนิม", "การหลอมละลาย", "การเปลี่ยนสี", "การแตกร้าว"], correct: 0 },
        { q: "Besides its use in metal coatings, zinc is also an important...", qTh: "นอกจากการใช้เคลือบโลหะแล้ว สังกะสียังเป็นสิ่งสำคัญในด้านใด", choices: ["Nutrient the body needs in small amounts", "Radioactive fuel", "Type of noble gas", "Liquid at room temperature"], choicesTh: ["สารอาหารที่ร่างกายต้องการในปริมาณเล็กน้อย", "เชื้อเพลิงกัมมันตรังสี", "ชนิดของแก๊สมีตระกูล", "ของเหลวที่อุณหภูมิห้อง"], correct: 0 }
      ]},
      31: { name: "Gallium", questions: [
        { q: "What is the chemical symbol for gallium?", qTh: "สัญลักษณ์ทางเคมีของแกลเลียมคืออะไร", choices: ["Ga", "Ge", "Gd", "Gm"], choicesTh: ["Ga", "Ge", "Gd", "Gm"], correct: 0 },
        { q: "Gallium has a strange party trick: what happens to a solid piece of it in your hand?", qTh: "แกลเลียมมีเล่ห์กลแปลกๆ นั่นคือจะเกิดอะไรขึ้นกับก้อนแข็งของมันเมื่ออยู่ในมือคุณ", choices: ["It melts, since its melting point is just above room temperature", "It turns into gas instantly", "It explodes", "It freezes your skin"], choicesTh: ["มันละลาย เพราะจุดหลอมเหลวของมันสูงกว่าอุณหภูมิห้องเพียงเล็กน้อย", "มันกลายเป็นแก๊สทันที", "มันระเบิด", "มันทำให้ผิวหนังแข็งตัว"], correct: 0 },
        { q: "Gallium is an important material used to make what kind of electronics?", qTh: "แกลเลียมเป็นวัสดุสำคัญที่ใช้ทำอุปกรณ์อิเล็กทรอนิกส์ชนิดใด", choices: ["LEDs and semiconductors", "Glass bottles", "Rubber tires", "Steel beams"], choicesTh: ["ไฟ LED และสารกึ่งตัวนำ", "ขวดแก้ว", "ยางรถยนต์", "คานเหล็ก"], correct: 0 }
      ]},
      32: { name: "Germanium", questions: [
        { q: "What is the chemical symbol for germanium?", qTh: "สัญลักษณ์ทางเคมีของเจอร์เมเนียมคืออะไร", choices: ["Ge", "Ga", "Gm", "Gr"], choicesTh: ["Ge", "Ga", "Gm", "Gr"], correct: 0 },
        { q: "Germanium is a metalloid used to make what kind of cables that carry internet data as light?", qTh: "เจอร์เมเนียมเป็นธาตุกึ่งโลหะที่ใช้ทำสายเคเบิลชนิดใดที่ส่งข้อมูลอินเทอร์เน็ตด้วยแสง", choices: ["Fiber-optic cables", "Copper wiring", "Power lines", "Extension cords"], choicesTh: ["สายใยแก้วนำแสง", "สายไฟทองแดง", "สายไฟฟ้าแรงสูง", "สายไฟต่อพ่วง"], correct: 0 },
        { q: "Germanium is also used in the lenses of what kind of equipment that detects heat?", qTh: "เจอร์เมเนียมยังถูกใช้ในเลนส์ของอุปกรณ์ชนิดใดที่ตรวจจับความร้อน", choices: ["Infrared and night-vision optics", "Regular eyeglasses", "Telescopes for visible light", "Microscope slides"], choicesTh: ["อุปกรณ์ตรวจจับอินฟราเรดและมองเห็นในที่มืด", "แว่นตาทั่วไป", "กล้องโทรทรรศน์แสงที่มองเห็นได้", "แผ่นสไลด์กล้องจุลทรรศน์"], correct: 0 }
      ]},
      33: { name: "Arsenic", questions: [
        { q: "What is the chemical symbol for arsenic?", qTh: "สัญลักษณ์ทางเคมีของสารหนู (อาร์เซนิก) คืออะไร", choices: ["As", "Ar", "Ac", "An"], choicesTh: ["As", "Ar", "Ac", "An"], correct: 0 },
        { q: "Arsenic is historically infamous for being used as a...", qTh: "ในอดีตสารหนูขึ้นชื่อในทางไม่ดีจากการถูกใช้เป็นอะไร", choices: ["Poison", "Sweetener", "Fuel", "Fertilizer only"], choicesTh: ["ยาพิษ", "สารให้ความหวาน", "เชื้อเพลิง", "ปุ๋ยเท่านั้น"], correct: 0 },
        { q: "Arsenic is classified as what kind of element, with properties of both metals and nonmetals?", qTh: "สารหนูถูกจัดเป็นธาตุประเภทใด ซึ่งมีสมบัติทั้งของโลหะและอโลหะ", choices: ["A metalloid", "A noble gas", "An alkali metal", "A halogen"], choicesTh: ["ธาตุกึ่งโลหะ", "แก๊สมีตระกูล", "โลหะแอลคาไล", "ธาตุแฮโลเจน"], correct: 0 }
      ]},
      34: { name: "Selenium", questions: [
        { q: "What is the chemical symbol for selenium?", qTh: "สัญลักษณ์ทางเคมีของซีลีเนียมคืออะไร", choices: ["Se", "Sl", "Sn", "Sm"], choicesTh: ["Se", "Sl", "Sn", "Sm"], correct: 0 },
        { q: "Selenium is an essential nutrient found in large amounts in which food?", qTh: "ซีลีเนียมเป็นสารอาหารที่จำเป็น พบได้ในปริมาณมากในอาหารชนิดใด", choices: ["Brazil nuts", "Oranges", "Bread", "Rice"], choicesTh: ["ถั่วบราซิล", "ส้ม", "ขนมปัง", "ข้าว"], correct: 0 },
        { q: "Selenium's conductivity changes with light, which made it useful in early...", qTh: "ความสามารถในการนำไฟฟ้าของซีลีเนียมเปลี่ยนไปตามแสง ซึ่งทำให้มันมีประโยชน์ในยุคแรกของสิ่งใด", choices: ["Solar cells and photocopiers", "Batteries", "Light bulb filaments", "Glass windows"], choicesTh: ["เซลล์สุริยะและเครื่องถ่ายเอกสาร", "แบตเตอรี่", "ไส้หลอดไฟ", "กระจกหน้าต่าง"], correct: 0 }
      ]},
      35: { name: "Bromine", questions: [
        { q: "What is the chemical symbol for bromine?", qTh: "สัญลักษณ์ทางเคมีของโบรมีนคืออะไร", choices: ["Br", "Bo", "Bm", "Bi"], choicesTh: ["Br", "Bo", "Bm", "Bi"], correct: 0 },
        { q: "Bromine is one of only two elements that exist as this state of matter at room temperature. Which?", qTh: "โบรมีนเป็นหนึ่งในสองธาตุเท่านั้นที่มีสถานะนี้ที่อุณหภูมิห้อง สถานะใด", choices: ["Liquid", "Gas", "Solid", "Plasma"], choicesTh: ["ของเหลว", "แก๊ส", "ของแข็ง", "พลาสมา"], correct: 0 },
        { q: "Bromine compounds have historically been used in what kind of safety products?", qTh: "สารประกอบโบรมีนถูกใช้มาแต่ในอดีตในผลิตภัณฑ์เพื่อความปลอดภัยชนิดใด", choices: ["Flame retardants", "Sunscreens", "Fire extinguisher foam only", "Life jackets"], choicesTh: ["สารหน่วงไฟ", "ครีมกันแดด", "โฟมดับเพลิงเท่านั้น", "เสื้อชูชีพ"], correct: 0 }
      ]},
      36: { name: "Krypton", questions: [
        { q: "What is the chemical symbol for krypton?", qTh: "สัญลักษณ์ทางเคมีของคริปทอนคืออะไร", choices: ["Kr", "Kp", "Ky", "Kn"], choicesTh: ["Kr", "Kp", "Ky", "Kn"], correct: 0 },
        { q: "Krypton gas is used to fill some energy-efficient light bulbs and what kind of precision light devices?", qTh: "แก๊สคริปทอนถูกใช้เติมในหลอดไฟประหยัดพลังงานบางชนิดและอุปกรณ์แสงความแม่นยำสูงชนิดใด", choices: ["Lasers", "Flashlights", "Candles", "Neon signs"], choicesTh: ["เลเซอร์", "ไฟฉาย", "เทียนไข", "ป้ายไฟนีออน"], correct: 0 },
        { q: "Krypton belongs to which group of elements that rarely react with anything?", qTh: "คริปทอนอยู่ในกลุ่มธาตุใดที่แทบไม่ทำปฏิกิริยากับสิ่งใดเลย", choices: ["Noble gases", "Halogens", "Alkali metals", "Transition metals"], choicesTh: ["แก๊สมีตระกูล", "ธาตุแฮโลเจน", "โลหะแอลคาไล", "โลหะทรานซิชัน"], correct: 0 }
      ]},
      37: { name: "Rubidium", questions: [
        { q: "What is the chemical symbol for rubidium?", qTh: "สัญลักษณ์ทางเคมีของรูบิเดียมคืออะไร", choices: ["Rb", "Ru", "Rd", "Rn"], choicesTh: ["Rb", "Ru", "Rd", "Rn"], correct: 0 },
        { q: "Like sodium and potassium, rubidium is a highly reactive metal that reacts violently with...", qTh: "เช่นเดียวกับโซเดียมและโพแทสเซียม รูบิเดียมเป็นโลหะที่ว่องไวต่อปฏิกิริยาสูงและทำปฏิกิริยาอย่างรุนแรงกับสิ่งใด", choices: ["Water", "Oxygen only when heated", "Glass", "Plastic"], choicesTh: ["น้ำ", "ออกซิเจนเมื่อได้รับความร้อนเท่านั้น", "แก้ว", "พลาสติก"], correct: 0 },
        { q: "Rubidium's very precise vibrations make it useful in building what kind of timekeeping device?", qTh: "การสั่นที่แม่นยำมากของรูบิเดียมทำให้มีประโยชน์ในการสร้างอุปกรณ์บอกเวลาชนิดใด", choices: ["Atomic clocks", "Sundials", "Wristwatches", "Metronomes"], choicesTh: ["นาฬิกาอะตอม", "นาฬิกาแดด", "นาฬิกาข้อมือ", "เครื่องเคาะจังหวะ"], correct: 0 }
      ]},
      38: { name: "Strontium", questions: [
        { q: "What is the chemical symbol for strontium?", qTh: "สัญลักษณ์ทางเคมีของสทรอนเชียมคืออะไร", choices: ["Sr", "St", "So", "Sn"], choicesTh: ["Sr", "St", "So", "Sn"], correct: 0 },
        { q: "Strontium compounds are used in fireworks to create what colored flame?", qTh: "สารประกอบสทรอนเชียมถูกใช้ในดอกไม้ไฟเพื่อสร้างเปลวไฟสีใด", choices: ["Bright red", "Bright green", "Deep blue", "Bright yellow"], choicesTh: ["แดงสด", "เขียวสด", "น้ำเงินเข้ม", "เหลืองสด"], correct: 0 },
        { q: "Strontium's chemical behavior is similar to which other alkaline earth metal, which is why it can build up in bones like calcium does?", qTh: "พฤติกรรมทางเคมีของสทรอนเชียมคล้ายกับโลหะแอลคาไลน์เอิร์ทชนิดใด จึงสามารถสะสมในกระดูกได้เหมือนแคลเซียม", choices: ["Calcium", "Sodium", "Iron", "Copper"], choicesTh: ["แคลเซียม", "โซเดียม", "เหล็ก", "ทองแดง"], correct: 0 }
      ]},
      39: { name: "Yttrium", questions: [
        { q: "What is the chemical symbol for yttrium?", qTh: "สัญลักษณ์ทางเคมีของอิตเทรียมคืออะไร", choices: ["Y", "Yt", "Yr", "Ym"], choicesTh: ["Y", "Yt", "Yr", "Ym"], correct: 0 },
        { q: "Yttrium compounds are used to make the red color in what kind of screens?", qTh: "สารประกอบอิตเทรียมถูกใช้สร้างสีแดงในหน้าจอชนิดใด", choices: ["Older TV and LED screens", "Black-and-white film", "Chalkboards", "Solar panels"], choicesTh: ["จอทีวีรุ่นเก่าและจอ LED", "ฟิล์มขาวดำ", "กระดานชอล์ก", "แผงโซลาร์เซลล์"], correct: 0 },
        { q: "Even though it's technically a transition metal, yttrium is usually grouped and studied alongside which family of elements?", qTh: "แม้ว่าโดยทางเทคนิคแล้วอิตเทรียมจะเป็นโลหะทรานซิชัน แต่มักถูกจัดกลุ่มและศึกษาร่วมกับตระกูลธาตุใด", choices: ["The lanthanides (rare earth elements)", "The noble gases", "The halogens", "The alkali metals"], choicesTh: ["แลนทาไนด์ (ธาตุหายาก)", "แก๊สมีตระกูล", "ธาตุแฮโลเจน", "โลหะแอลคาไล"], correct: 0 }
      ]},
      40: { name: "Zirconium", questions: [
        { q: "What is the chemical symbol for zirconium?", qTh: "สัญลักษณ์ทางเคมีของเซอร์โคเนียมคืออะไร", choices: ["Zr", "Zi", "Zc", "Zm"], choicesTh: ["Zr", "Zi", "Zc", "Zm"], correct: 0 },
        { q: "Zirconium is used to build the fuel tubes inside nuclear reactors because it barely absorbs...", qTh: "เซอร์โคเนียมถูกใช้สร้างท่อเชื้อเพลิงภายในเครื่องปฏิกรณ์นิวเคลียร์ เพราะมันแทบไม่ดูดซับสิ่งใด", choices: ["Neutrons", "Heat", "Water", "Electricity"], choicesTh: ["นิวตรอน", "ความร้อน", "น้ำ", "ไฟฟ้า"], correct: 0 },
        { q: "Cubic zirconia, a popular diamond substitute in jewelry, is made from a compound of...", qTh: "คิวบิกเซอร์โคเนีย ซึ่งเป็นสารทดแทนเพชรที่นิยมใช้ในเครื่องประดับ ทำจากสารประกอบของสิ่งใด", choices: ["Zirconium", "Zinc", "Zinc oxide only", "Silicon"], choicesTh: ["เซอร์โคเนียม", "สังกะสี", "สังกะสีออกไซด์เท่านั้น", "ซิลิคอน"], correct: 0 }
      ]},
      41: { name: "Niobium", questions: [
        { q: "What is the chemical symbol for niobium?", qTh: "สัญลักษณ์ทางเคมีของไนโอเบียมคืออะไร", choices: ["Nb", "Ni", "No", "Nm"], choicesTh: ["Nb", "Ni", "No", "Nm"], correct: 0 },
        { q: "Niobium is used to make superconducting magnets, like the powerful ones found in...", qTh: "ไนโอเบียมถูกใช้ทำแม่เหล็กตัวนำยิ่งยวด เช่นแม่เหล็กกำลังสูงที่พบใน", choices: ["MRI machines", "Toasters", "Batteries", "Light bulbs"], choicesTh: ["เครื่อง MRI", "เครื่องปิ้งขนมปัง", "แบตเตอรี่", "หลอดไฟ"], correct: 0 },
        { q: "Niobium is named after Niobe, a figure from what mythology?", qTh: "ไนโอเบียมถูกตั้งชื่อตามไนโอบี ตัวละครจากเทพปกรณัมใด", choices: ["Greek mythology", "Norse mythology", "Egyptian mythology", "Roman mythology"], choicesTh: ["เทพปกรณัมกรีก", "เทพปกรณัมนอร์ส", "เทพปกรณัมอียิปต์", "เทพปกรณัมโรมัน"], correct: 0 }
      ]},
      42: { name: "Molybdenum", questions: [
        { q: "What is the chemical symbol for molybdenum?", qTh: "สัญลักษณ์ทางเคมีของโมลิบดีนัมคืออะไร", choices: ["Mo", "Ml", "Md", "My"], choicesTh: ["Mo", "Ml", "Md", "My"], correct: 0 },
        { q: "Molybdenum is added to steel to make alloys that are strong and resistant to...", qTh: "โมลิบดีนัมถูกเติมลงในเหล็กกล้าเพื่อทำโลหะผสมที่แข็งแรงและทนต่อสิ่งใด", choices: ["Heat", "Water", "Electricity", "Light"], choicesTh: ["ความร้อน", "น้ำ", "ไฟฟ้า", "แสง"], correct: 0 },
        { q: "In small amounts, molybdenum is also an essential...", qTh: "ในปริมาณเล็กน้อย โมลิบดีนัมยังเป็นสิ่งที่จำเป็นต่ออะไร", choices: ["Nutrient for living things", "Fuel source", "Type of noble gas", "Radioactive tracer"], choicesTh: ["สารอาหารสำหรับสิ่งมีชีวิต", "แหล่งเชื้อเพลิง", "ชนิดของแก๊สมีตระกูล", "สารติดตามกัมมันตรังสี"], correct: 0 }
      ]},
      43: { name: "Technetium", questions: [
        { q: "What is the chemical symbol for technetium?", qTh: "สัญลักษณ์ทางเคมีของเทคนีเชียมคืออะไร", choices: ["Tc", "Te", "Tn", "Th"], choicesTh: ["Tc", "Te", "Tn", "Th"], correct: 0 },
        { q: "Technetium was the first element ever made artificially rather than found in nature, and has no...", qTh: "เทคนีเชียมเป็นธาตุแรกที่ถูกสร้างขึ้นโดยมนุษย์แทนที่จะพบในธรรมชาติ และไม่มีสิ่งใด", choices: ["Stable isotopes", "Electrons", "Protons", "Uses at all"], choicesTh: ["ไอโซโทปที่เสถียร", "อิเล็กตรอน", "โปรตอน", "การใช้งานใดๆ เลย"], correct: 0 },
        { q: "Technetium is widely used in hospitals today as a...", qTh: "ปัจจุบันเทคนีเชียมถูกใช้กันอย่างแพร่หลายในโรงพยาบาลในฐานะอะไร", choices: ["Radioactive tracer for medical imaging", "Anesthetic", "Painkiller", "Antibiotic"], choicesTh: ["สารติดตามกัมมันตรังสีสำหรับการถ่ายภาพทางการแพทย์", "ยาสลบ", "ยาแก้ปวด", "ยาปฏิชีวนะ"], correct: 0 }
      ]},
      44: { name: "Ruthenium", questions: [
        { q: "What is the chemical symbol for ruthenium?", qTh: "สัญลักษณ์ทางเคมีของรูทีเนียมคืออะไร", choices: ["Ru", "Rt", "Rh", "Rn"], choicesTh: ["Ru", "Rt", "Rh", "Rn"], correct: 0 },
        { q: "Ruthenium is often added to platinum and palladium to make them...", qTh: "รูทีเนียมมักถูกเติมลงในแพลตทินัมและแพลเลเดียมเพื่อทำให้เป็นอย่างไร", choices: ["Harder", "Softer", "Radioactive", "Colorless"], choicesTh: ["แข็งขึ้น", "อ่อนลง", "มีกัมมันตรังสี", "ไม่มีสี"], correct: 0 },
        { q: "Ruthenium is part of a rare group of metals often found together, known as the...", qTh: "รูทีเนียมเป็นส่วนหนึ่งของกลุ่มโลหะหายากที่มักพบร่วมกัน ซึ่งรู้จักกันในชื่อใด", choices: ["Platinum group metals", "Alkali metals", "Halogens", "Noble gases"], choicesTh: ["โลหะกลุ่มแพลตทินัม", "โลหะแอลคาไล", "ธาตุแฮโลเจน", "แก๊สมีตระกูล"], correct: 0 }
      ]},
      45: { name: "Rhodium", questions: [
        { q: "What is the chemical symbol for rhodium?", qTh: "สัญลักษณ์ทางเคมีของโรเดียมคืออะไร", choices: ["Rh", "Ro", "Rd", "Rm"], choicesTh: ["Rh", "Ro", "Rd", "Rm"], correct: 0 },
        { q: "Rhodium is used to coat the inside of car catalytic converters to help reduce...", qTh: "โรเดียมถูกใช้เคลือบภายในตัวเร่งปฏิกิริยาของรถยนต์เพื่อช่วยลดสิ่งใด", choices: ["Pollution", "Engine noise", "Fuel use directly", "Weight"], choicesTh: ["มลพิษ", "เสียงเครื่องยนต์", "การใช้เชื้อเพลิงโดยตรง", "น้ำหนัก"], correct: 0 },
        { q: "Rhodium is considered one of the...", qTh: "โรเดียมถูกจัดว่าเป็นหนึ่งในอะไร", choices: ["Rarest and most valuable precious metals", "Most common metals on Earth", "Lightest metals known", "Most reactive metals known"], choicesTh: ["โลหะมีค่าที่หายากและมีมูลค่าสูงที่สุด", "โลหะที่พบได้ทั่วไปที่สุดบนโลก", "โลหะที่เบาที่สุดเท่าที่รู้จัก", "โลหะที่ว่องไวต่อปฏิกิริยามากที่สุดเท่าที่รู้จัก"], correct: 0 }
      ]},
      46: { name: "Palladium", questions: [
        { q: "What is the chemical symbol for palladium?", qTh: "สัญลักษณ์ทางเคมีของแพลเลเดียมคืออะไร", choices: ["Pd", "Pl", "Pa", "Pm"], choicesTh: ["Pd", "Pl", "Pa", "Pm"], correct: 0 },
        { q: "Like rhodium, palladium is used inside cars to help reduce pollution as part of the...", qTh: "เช่นเดียวกับโรเดียม แพลเลเดียมถูกใช้ภายในรถยนต์เพื่อช่วยลดมลพิษ โดยเป็นส่วนหนึ่งของอะไร", choices: ["Catalytic converter", "Engine block", "Battery", "Air conditioning system"], choicesTh: ["ตัวเร่งปฏิกิริยา", "เสื้อสูบเครื่องยนต์", "แบตเตอรี่", "ระบบปรับอากาศ"], correct: 0 },
        { q: "Palladium has an unusual ability to absorb large amounts of what gas?", qTh: "แพลเลเดียมมีความสามารถพิเศษในการดูดซับแก๊สชนิดใดในปริมาณมาก", choices: ["Hydrogen", "Oxygen", "Nitrogen", "Helium"], choicesTh: ["ไฮโดรเจน", "ออกซิเจน", "ไนโตรเจน", "ฮีเลียม"], correct: 0 }
      ]},
      47: { name: "Silver", questions: [
        { q: "What is the chemical symbol for silver?", qTh: "สัญลักษณ์ทางเคมีของเงินคืออะไร", choices: ["Ag", "Si", "Sv", "Ar"], choicesTh: ["Ag", "Si", "Sv", "Ar"], correct: 0 },
        { q: "Silver is the best conductor of electricity of any element, even better than which more commonly used metal?", qTh: "เงินเป็นตัวนำไฟฟ้าที่ดีที่สุดในบรรดาธาตุทั้งหมด ดีกว่าโลหะที่ใช้กันทั่วไปชนิดใด", choices: ["Copper", "Iron", "Aluminum", "Gold"], choicesTh: ["ทองแดง", "เหล็ก", "อะลูมิเนียม", "ทองคำ"], correct: 0 },
        { q: "Silver has long been used to make jewelry, mirrors, and even...", qTh: "เงินถูกใช้มายาวนานในการทำเครื่องประดับ กระจกเงา และแม้แต่สิ่งใด", choices: ["Coins", "Rubber", "Fertilizer", "Glass"], choicesTh: ["เหรียญกษาปณ์", "ยาง", "ปุ๋ย", "แก้ว"], correct: 0 }
      ]},
      48: { name: "Cadmium", questions: [
        { q: "What is the chemical symbol for cadmium?", qTh: "สัญลักษณ์ทางเคมีของแคดเมียมคืออะไร", choices: ["Cd", "Ca", "Cm", "Cn"], choicesTh: ["Cd", "Ca", "Cm", "Cn"], correct: 0 },
        { q: "Cadmium is a heavy metal that is well known for being...", qTh: "แคดเมียมเป็นโลหะหนักที่ขึ้นชื่อว่าเป็นอย่างไร", choices: ["Toxic", "Edible in small amounts", "Lighter than air", "A noble gas"], choicesTh: ["มีพิษ", "รับประทานได้ในปริมาณเล็กน้อย", "เบากว่าอากาศ", "เป็นแก๊สมีตระกูล"], correct: 0 },
        { q: "Cadmium was historically used to make what kind of rechargeable battery?", qTh: "ในอดีตแคดเมียมถูกใช้ทำแบตเตอรี่แบบชาร์จไฟได้ชนิดใด", choices: ["Nickel-cadmium (Ni-Cd) batteries", "Lithium-ion batteries", "Lead-acid batteries", "Alkaline batteries"], choicesTh: ["แบตเตอรี่นิกเกิล-แคดเมียม (Ni-Cd)", "แบตเตอรี่ลิเธียมไอออน", "แบตเตอรี่ตะกั่ว-กรด", "แบตเตอรี่อัลคาไลน์"], correct: 0 }
      ]},
      49: { name: "Indium", questions: [
        { q: "What is the chemical symbol for indium?", qTh: "สัญลักษณ์ทางเคมีของอินเดียมคืออะไร", choices: ["In", "Id", "Iu", "Im"], choicesTh: ["In", "Id", "Iu", "Im"], correct: 0 },
        { q: "A compound of indium coats the screens of phones and tablets so they can be both transparent and...", qTh: "สารประกอบของอินเดียมเคลือบหน้าจอโทรศัพท์และแท็บเล็ต ทำให้หน้าจอโปร่งใสและสามารถทำอะไรได้ด้วย", choices: ["Conduct electricity for touch sensing", "Waterproof", "Shatterproof", "Anti-glare"], choicesTh: ["นำไฟฟ้าเพื่อรับสัมผัส", "กันน้ำ", "ทนแรงกระแทกไม่แตก", "ลดแสงสะท้อน"], correct: 0 },
        { q: "Indium is best described as a...", qTh: "อินเดียมถูกอธิบายได้ดีที่สุดว่าเป็นอะไร", choices: ["Soft, easily-bent metal", "Hard, brittle nonmetal", "Colorless gas", "Radioactive liquid"], choicesTh: ["โลหะอ่อนที่งอได้ง่าย", "อโลหะที่แข็งและเปราะ", "แก๊สไม่มีสี", "ของเหลวกัมมันตรังสี"], correct: 0 }
      ]},
      50: { name: "Tin", questions: [
        { q: "What is the chemical symbol for tin?", qTh: "สัญลักษณ์ทางเคมีของดีบุกคืออะไร", choices: ["Sn", "Ti", "Tn", "To"], choicesTh: ["Sn", "Ti", "Tn", "To"], correct: 0 },
        { q: "\"Tin cans\" are actually made of steel with a thin coating of tin to prevent...", qTh: "\"กระป๋องดีบุก\" แท้จริงแล้วทำจากเหล็กกล้าที่เคลือบดีบุกบางๆ เพื่อป้องกันสิ่งใด", choices: ["Rust", "Denting", "Melting", "Leaking flavor"], choicesTh: ["สนิม", "การบุบ", "การหลอมละลาย", "รสชาติรั่วไหล"], correct: 0 },
        { q: "Tin is also a key ingredient in solder, which is used to join together...", qTh: "ดีบุกยังเป็นส่วนประกอบสำคัญของตะกั่วบัดกรี ซึ่งใช้เชื่อมต่ออะไรเข้าด้วยกัน", choices: ["Electronic circuits and pipes", "Wooden furniture", "Fabric", "Concrete slabs"], choicesTh: ["วงจรอิเล็กทรอนิกส์และท่อ", "เฟอร์นิเจอร์ไม้", "ผ้า", "แผ่นคอนกรีต"], correct: 0 }
      ]},
      51: { name: "Antimony", questions: [
        { q: "What is the chemical symbol for antimony?", qTh: "สัญลักษณ์ทางเคมีของพลวง (แอนติโมนี) คืออะไร", choices: ["Sb", "An", "At", "Am"], choicesTh: ["Sb", "An", "At", "Am"], correct: 0 },
        { q: "Antimony's chemical symbol, Sb, comes from its Latin name. What is it?", qTh: "สัญลักษณ์ทางเคมีของพลวง (Sb) มาจากชื่อภาษาละติน ชื่อนั้นคืออะไร", choices: ["Stibium", "Antimonium", "Argentum", "Aurum"], choicesTh: ["Stibium", "Antimonium", "Argentum", "Aurum"], correct: 0 },
        { q: "Antimony compounds are commonly used in...", qTh: "สารประกอบพลวงมักถูกใช้ในสิ่งใด", choices: ["Flame-retardant materials", "Sunscreen", "Toothpaste", "Fertilizer"], choicesTh: ["วัสดุหน่วงไฟ", "ครีมกันแดด", "ยาสีฟัน", "ปุ๋ย"], correct: 0 }
      ]},
      52: { name: "Tellurium", questions: [
        { q: "What is the chemical symbol for tellurium?", qTh: "สัญลักษณ์ทางเคมีของเทลลูเรียมคืออะไร", choices: ["Te", "Tl", "Tu", "Tm"], choicesTh: ["Te", "Tl", "Tu", "Tm"], correct: 0 },
        { q: "People who are exposed to tellurium compounds often notice their breath smells like...", qTh: "ผู้ที่สัมผัสสารประกอบเทลลูเรียมมักสังเกตว่าลมหายใจมีกลิ่นเหมือนอะไร", choices: ["Garlic", "Rotten eggs", "Bleach", "Mint"], choicesTh: ["กระเทียม", "ไข่เน่า", "น้ำยาฟอกขาว", "มินต์"], correct: 0 },
        { q: "Tellurium, combined with cadmium, is used to make a common type of...", qTh: "เทลลูเรียมเมื่อรวมกับแคดเมียม ถูกใช้ทำสิ่งที่พบได้ทั่วไปชนิดใด", choices: ["Solar panel", "Battery", "Light bulb", "Magnet"], choicesTh: ["แผงโซลาร์เซลล์", "แบตเตอรี่", "หลอดไฟ", "แม่เหล็ก"], correct: 0 }
      ]},
      53: { name: "Iodine", questions: [
        { q: "What is the chemical symbol for iodine?", qTh: "สัญลักษณ์ทางเคมีของไอโอดีนคืออะไร", choices: ["I", "Io", "Id", "In"], choicesTh: ["I", "Io", "Id", "In"], correct: 0 },
        { q: "Iodine is essential for the thyroid gland, which is why it's often added to...", qTh: "ไอโอดีนจำเป็นต่อต่อมไทรอยด์ จึงมักถูกเติมลงในสิ่งใด", choices: ["Table salt", "Drinking water", "Sunscreen", "Milk"], choicesTh: ["เกลือแกง", "น้ำดื่ม", "ครีมกันแดด", "นม"], correct: 0 },
        { q: "When heated, solid iodine turns directly into a striking purple vapor. What is this process called?", qTh: "เมื่อได้รับความร้อน ไอโอดีนแข็งจะกลายเป็นไอสีม่วงสดโดยตรง กระบวนการนี้เรียกว่าอะไร", choices: ["Sublimation", "Evaporation", "Condensation", "Fusion"], choicesTh: ["การระเหิด", "การระเหย", "การควบแน่น", "การหลอมรวม"], correct: 0 }
      ]},
      54: { name: "Xenon", questions: [
        { q: "What is the chemical symbol for xenon?", qTh: "สัญลักษณ์ทางเคมีของซีนอนคืออะไร", choices: ["Xe", "Xn", "Xo", "Xa"], choicesTh: ["Xe", "Xn", "Xo", "Xa"], correct: 0 },
        { q: "Xenon gas is used in some car headlights and camera equipment because it produces a bright...", qTh: "แก๊สซีนอนถูกใช้ในไฟหน้ารถยนต์บางรุ่นและอุปกรณ์กล้องถ่ายรูป เพราะมันให้แสงที่สว่างแบบใด", choices: ["Flash of light", "Colored smoke", "Magnetic field", "Sound"], choicesTh: ["แสงแฟลช", "ควันสี", "สนามแม่เหล็ก", "เสียง"], correct: 0 },
        { q: "Xenon belongs to which family of gases known for barely reacting with anything?", qTh: "ซีนอนอยู่ในตระกูลแก๊สใดที่ขึ้นชื่อว่าแทบไม่ทำปฏิกิริยากับสิ่งใดเลย", choices: ["Noble gases", "Halogens", "Alkali metals", "Alkaline earth metals"], choicesTh: ["แก๊สมีตระกูล", "ธาตุแฮโลเจน", "โลหะแอลคาไล", "โลหะแอลคาไลน์เอิร์ท"], correct: 0 }
      ]},
      55: { name: "Caesium", questions: [
        { q: "What is the chemical symbol for caesium?", qTh: "สัญลักษณ์ทางเคมีของซีเซียมคืออะไร", choices: ["Cs", "Ce", "Ca", "Cm"], choicesTh: ["Cs", "Ce", "Ca", "Cm"], correct: 0 },
        { q: "Caesium's extremely precise vibrations are used to define the exact length of a...", qTh: "การสั่นที่แม่นยำสูงมากของซีเซียมถูกใช้กำหนดความยาวที่แน่นอนของสิ่งใด", choices: ["Second", "Meter", "Kilogram", "Degree"], choicesTh: ["วินาที", "เมตร", "กิโลกรัม", "องศา"], correct: 0 },
        { q: "Caesium is an alkali metal that melts just above room temperature and reacts how with water?", qTh: "ซีเซียมเป็นโลหะแอลคาไลที่หลอมเหลวสูงกว่าอุณหภูมิห้องเพียงเล็กน้อย และทำปฏิกิริยากับน้ำอย่างไร", choices: ["Explosively", "Not at all", "Very slowly", "Only when frozen first"], choicesTh: ["อย่างรุนแรงจนระเบิด", "ไม่ทำปฏิกิริยาเลย", "อย่างช้ามาก", "ทำปฏิกิริยาเมื่อแช่แข็งก่อนเท่านั้น"], correct: 0 }
      ]},
      56: { name: "Barium", questions: [
        { q: "What is the chemical symbol for barium?", qTh: "สัญลักษณ์ทางเคมีของแบเรียมคืออะไร", choices: ["Ba", "Br", "Bo", "By"], choicesTh: ["Ba", "Br", "Bo", "By"], correct: 0 },
        { q: "Before certain X-rays, patients may drink a \"barium meal\" because barium shows up clearly on...", qTh: "ก่อนการเอกซเรย์บางประเภท ผู้ป่วยอาจต้องดื่ม \"แบเรียมมีล\" เพราะแบเรียมปรากฏชัดเจนบนสิ่งใด", choices: ["X-ray images", "Blood tests", "Skin scans", "Hearing tests"], choicesTh: ["ภาพเอกซเรย์", "การตรวจเลือด", "การสแกนผิวหนัง", "การทดสอบการได้ยิน"], correct: 0 },
        { q: "Barium compounds are used in fireworks to produce what color flame?", qTh: "สารประกอบแบเรียมถูกใช้ในดอกไม้ไฟเพื่อสร้างเปลวไฟสีใด", choices: ["Green", "Red", "Purple", "Orange"], choicesTh: ["เขียว", "แดง", "ม่วง", "ส้ม"], correct: 0 }
      ]},
      57: { name: "Lanthanum", questions: [
        { q: "What is the chemical symbol for lanthanum?", qTh: "สัญลักษณ์ทางเคมีของแลนทานัมคืออะไร", choices: ["La", "Ln", "Lt", "Lm"], choicesTh: ["La", "Ln", "Lt", "Lm"], correct: 0 },
        { q: "Lanthanum is the first element in a special row of the periodic table usually shown at the bottom. What is that row called?", qTh: "แลนทานัมเป็นธาตุแรกในแถวพิเศษของตารางธาตุที่มักแสดงไว้ด้านล่าง แถวนี้เรียกว่าอะไร", choices: ["Lanthanides", "Actinides", "Halogens", "Noble gases"], choicesTh: ["แลนทาไนด์", "แอกทิไนด์", "ธาตุแฮโลเจน", "แก๊สมีตระกูล"], correct: 0 },
        { q: "Lanthanum compounds are used to make high-quality...", qTh: "สารประกอบแลนทานัมถูกใช้ทำสิ่งใดที่มีคุณภาพสูง", choices: ["Camera and telescope lenses", "Rubber tires", "Sunscreen", "Table salt"], choicesTh: ["เลนส์กล้องถ่ายรูปและกล้องโทรทรรศน์", "ยางรถยนต์", "ครีมกันแดด", "เกลือแกง"], correct: 0 }
      ]},
      58: { name: "Cerium", questions: [
        { q: "What is the chemical symbol for cerium?", qTh: "สัญลักษณ์ทางเคมีของซีเรียมคืออะไร", choices: ["Ce", "Cr", "Cm", "Co"], choicesTh: ["Ce", "Cr", "Cm", "Co"], correct: 0 },
        { q: "Cerium is the most abundant of a group of elements often nicknamed the...", qTh: "ซีเรียมมีปริมาณมากที่สุดในกลุ่มธาตุที่มักถูกเรียกว่าอะไร", choices: ["Rare earth elements", "Noble gases", "Halogens", "Precious metals"], choicesTh: ["ธาตุหายาก", "แก๊สมีตระกูล", "ธาตุแฮโลเจน", "โลหะมีค่า"], correct: 0 },
        { q: "A cerium alloy is used to make the sparking metal inside common...", qTh: "โลหะผสมซีเรียมถูกใช้ทำโลหะที่ทำให้เกิดประกายไฟภายในสิ่งที่พบได้ทั่วไปชนิดใด", choices: ["Cigarette lighters", "Batteries", "Light bulbs", "Solar panels"], choicesTh: ["ไฟแช็กบุหรี่", "แบตเตอรี่", "หลอดไฟ", "แผงโซลาร์เซลล์"], correct: 0 }
      ]},
      59: { name: "Praseodymium", questions: [
        { q: "What is the chemical symbol for praseodymium?", qTh: "สัญลักษณ์ทางเคมีของเพรซีโอดิเมียมคืออะไร", choices: ["Pr", "Pa", "Pd", "Pm"], choicesTh: ["Pr", "Pa", "Pd", "Pm"], correct: 0 },
        { q: "Praseodymium's name comes from Greek words meaning \"green twin,\" describing the color of its...", qTh: "ชื่อของเพรซีโอดิเมียมมาจากคำภาษากรีกที่แปลว่า \"ฝาแฝดสีเขียว\" ซึ่งบรรยายสีของสิ่งใด", choices: ["Oxide and salts", "Flame in fireworks", "Metal surface when polished", "Glow under UV light"], choicesTh: ["ออกไซด์และเกลือของมัน", "เปลวไฟในดอกไม้ไฟ", "ผิวโลหะเมื่อขัดเงา", "การเรืองแสงภายใต้แสงยูวี"], correct: 0 },
        { q: "Praseodymium is used to color glass and ceramics, and is also mixed into strong...", qTh: "เพรซีโอดิเมียมถูกใช้ทำให้แก้วและเซรามิกมีสี และยังถูกผสมลงในสิ่งที่แข็งแรงชนิดใดด้วย", choices: ["Magnets", "Batteries", "Adhesives", "Fertilizers"], choicesTh: ["แม่เหล็ก", "แบตเตอรี่", "กาว", "ปุ๋ย"], correct: 0 }
      ]}
};
